//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncTrayzor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SyncTrayzor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Antony Male..
        /// </summary>
        public static string AboutView_CreatedByAuthor {
            get {
                return ResourceManager.GetString("AboutView_CreatedByAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate now.
        /// </summary>
        public static string AboutView_Donate_Link {
            get {
                return ResourceManager.GetString("AboutView_Donate_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find SyncTrayzor useful?
        ///Please donate to my charity fundraising campaign..
        /// </summary>
        public static string AboutView_Donate_Text {
            get {
                return ResourceManager.GetString("AboutView_Donate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate again.
        /// </summary>
        public static string AboutView_DonateAgain_Link {
            get {
                return ResourceManager.GetString("AboutView_DonateAgain_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheers! Thanks for donating..
        /// </summary>
        public static string AboutView_DonateThanks {
            get {
                return ResourceManager.GetString("AboutView_DonateThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Download Page.
        /// </summary>
        public static string AboutView_DownloadNewVersion {
            get {
                return ResourceManager.GetString("AboutView_DownloadNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available: {0}.
        /// </summary>
        public static string AboutView_NewAppVersionAvailable {
            get {
                return ResourceManager.GetString("AboutView_NewAppVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released under the MIT license..
        /// </summary>
        public static string AboutView_ReleasedLicense {
            get {
                return ResourceManager.GetString("AboutView_ReleasedLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Open Source Licenses.
        /// </summary>
        public static string AboutView_ShowOtherLicenses {
            get {
                return ResourceManager.GetString("AboutView_ShowOtherLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing Version: {0}.
        /// </summary>
        public static string AboutView_SyncthingVersion {
            get {
                return ResourceManager.GetString("AboutView_SyncthingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string AboutView_UnknownVersion {
            get {
                return ResourceManager.GetString("AboutView_UnknownVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string AboutView_Version {
            get {
                return ResourceManager.GetString("AboutView_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0:p:1 conflicted file|{} conflicted files}..
        /// </summary>
        public static string BarAlertsView_Conflict_AlertText {
            get {
                return ResourceManager.GetString("BarAlertsView_Conflict_AlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve now..
        /// </summary>
        public static string BarAlertsView_Conflict_ResolveLink {
            get {
                return ResourceManager.GetString("BarAlertsView_Conflict_ResolveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following {0:p:folder has|folders have} failing file transfers: {0:l:{}|, }..
        /// </summary>
        public static string BarAlertsView_FailedTransfer_AlertText {
            get {
                return ResourceManager.GetString("BarAlertsView_FailedTransfer_AlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please see the Syncthing GUI or Console for clues..
        /// </summary>
        public static string BarAlertsView_FailedTransfer_Details {
            get {
                return ResourceManager.GetString("BarAlertsView_FailedTransfer_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following {0:p:device has|devices have} been paused because {0:p:it|they} connected using a metered network: {0:l:{}|, }..
        /// </summary>
        public static string BarAlertsView_PausedDevicesFromMetering_AlertText {
            get {
                return ResourceManager.GetString("BarAlertsView_PausedDevicesFromMetering_AlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string ConflictResolutionView_Button_Choose {
            get {
                return ResourceManager.GetString("ConflictResolutionView_Button_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Folder.
        /// </summary>
        public static string ConflictResolutionView_Button_ShowInFolder {
            get {
                return ResourceManager.GetString("ConflictResolutionView_Button_ShowInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the version of the file you want to keep. The other versions will be deleted..
        /// </summary>
        public static string ConflictResolutionView_ChooseDescription {
            get {
                return ResourceManager.GetString("ConflictResolutionView_ChooseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Newest.
        /// </summary>
        public static string ConflictResolutionView_ChooseNewest_Button {
            get {
                return ResourceManager.GetString("ConflictResolutionView_ChooseNewest_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chooses the &apos;Original&apos; file if its &apos;Last Modified&apos; date is newest, or the conflict which was created most recently.
        /// </summary>
        public static string ConflictResolutionView_ChooseNewest_Text {
            get {
                return ResourceManager.GetString("ConflictResolutionView_ChooseNewest_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Newest Conflict.
        /// </summary>
        public static string ConflictResolutionView_ChooseNewestConflict_Button {
            get {
                return ResourceManager.GetString("ConflictResolutionView_ChooseNewestConflict_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chooses the conflict which was created most recently&lt;.
        /// </summary>
        public static string ConflictResolutionView_ChooseNewestConflict_Text {
            get {
                return ResourceManager.GetString("ConflictResolutionView_ChooseNewestConflict_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Original.
        /// </summary>
        public static string ConflictResolutionView_ChooseOriginal_Button {
            get {
                return ResourceManager.GetString("ConflictResolutionView_ChooseOriginal_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takes the &apos;Original&apos; file from each conflict, and deletes all conflicting files.
        /// </summary>
        public static string ConflictResolutionView_ChooseOriginal_Text {
            get {
                return ResourceManager.GetString("ConflictResolutionView_ChooseOriginal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move deleted files to the recycle bin, rather than deleting permanently.
        /// </summary>
        public static string ConflictResolutionView_DeleteToRecycleBin {
            get {
                return ResourceManager.GetString("ConflictResolutionView_DeleteToRecycleBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolving this conflict failed: {0}.
        /// </summary>
        public static string ConflictResolutionView_Dialog_Failed_Message {
            get {
                return ResourceManager.GetString("ConflictResolutionView_Dialog_Failed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Failed.
        /// </summary>
        public static string ConflictResolutionView_Dialog_Failed_Title {
            get {
                return ResourceManager.GetString("ConflictResolutionView_Dialog_Failed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict Created.
        /// </summary>
        public static string ConflictResolutionView_Header_ConflictCreated {
            get {
                return ResourceManager.GetString("ConflictResolutionView_Header_ConflictCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicting File Name.
        /// </summary>
        public static string ConflictResolutionView_Header_ConflictingFileName {
            get {
                return ResourceManager.GetString("ConflictResolutionView_Header_ConflictingFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string ConflictResolutionView_Header_File {
            get {
                return ResourceManager.GetString("ConflictResolutionView_Header_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string ConflictResolutionView_Header_Folder {
            get {
                return ResourceManager.GetString("ConflictResolutionView_Header_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified.
        /// </summary>
        public static string ConflictResolutionView_Header_LastModified {
            get {
                return ResourceManager.GetString("ConflictResolutionView_Header_LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original File.
        /// </summary>
        public static string ConflictResolutionView_Header_OriginalFile {
            get {
                return ResourceManager.GetString("ConflictResolutionView_Header_OriginalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string ConflictResolutionView_Header_Size {
            get {
                return ResourceManager.GetString("ConflictResolutionView_Header_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ConflictResolutionView_Scanning_CancelButton {
            get {
                return ResourceManager.GetString("ConflictResolutionView_Scanning_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning....
        /// </summary>
        public static string ConflictResolutionView_Scanning_Label {
            get {
                return ResourceManager.GetString("ConflictResolutionView_Scanning_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No conflicts found. Good job!.
        /// </summary>
        public static string ConflictResolutionView_Status_NoConflicts {
            get {
                return ResourceManager.GetString("ConflictResolutionView_Status_NoConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No conflicts found (yet)....
        /// </summary>
        public static string ConflictResolutionView_Status_Scanning {
            get {
                return ResourceManager.GetString("ConflictResolutionView_Status_Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing is not running. Please start Syncthing..
        /// </summary>
        public static string ConflictResolutionView_Status_SyncthingNotRunning {
            get {
                return ResourceManager.GetString("ConflictResolutionView_Status_SyncthingNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict Resolver.
        /// </summary>
        public static string ConflictResolutionView_Title {
            get {
                return ResourceManager.GetString("ConflictResolutionView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected {0} conflicts. Choose how you want to resolve them. The other versions will be deleted..
        /// </summary>
        public static string ConfliectResolutionView_ChooseMultipleDescription {
            get {
                return ResourceManager.GetString("ConfliectResolutionView_ChooseMultipleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ConsoleView_ClearButton {
            get {
                return ResourceManager.GetString("ConsoleView_ClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string ConsoleView_PauseButton {
            get {
                return ResourceManager.GetString("ConsoleView_PauseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string ConsoleView_ResumeButton {
            get {
                return ResourceManager.GetString("ConsoleView_ResumeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ConsoleView_SettingsButton {
            get {
                return ResourceManager.GetString("ConsoleView_SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing Console.
        /// </summary>
        public static string ConsoleView_Title {
            get {
                return ResourceManager.GetString("ConsoleView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to kill all Syncthing processes, even those not managed by SyncTrayzor?
        ///
        ///This risks corrupting Syncthing&apos;s database. ONLY do this if you are unable to start Syncthing because another Syncthing process is currently running..
        /// </summary>
        public static string Dialog_ConfirmKillAllProcesses_Message {
            get {
                return ResourceManager.GetString("Dialog_ConfirmKillAllProcesses_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really?.
        /// </summary>
        public static string Dialog_ConfirmKillAllProcesses_Title {
            get {
                return ResourceManager.GetString("Dialog_ConfirmKillAllProcesses_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start Syncthing.
        ///
        ///Please read the log to determine the cause.
        ///
        ///If &quot;FATAL: Cannot open database&quot; appears, please close any other open instances of Syncthing. If SyncTrayzor crashed previously, there may still be zombine Syncthing processes alive. Please use the menu option &quot;Syncthing -&gt; Kill all Syncthing processes&quot; to stop them, then use &quot;Syncthing -&gt; Start&quot; to start Syncthing again..
        /// </summary>
        public static string Dialog_FailedToStartSyncthing_Message {
            get {
                return ResourceManager.GetString("Dialog_FailedToStartSyncthing_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing failed to start.
        /// </summary>
        public static string Dialog_FailedToStartSyncthing_Title {
            get {
                return ResourceManager.GetString("Dialog_FailedToStartSyncthing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start Syncthing: {0}
        ///
        ///This could be because Windows if set up to forbid executing files in AppData, or because you have anti-malware installed (e.g. CryptoPrevent ) which prevents executing files in AppData.
        ///
        ///Please adjust your settings / whitelists to allow &apos;{1}&apos; to execute.
        /// </summary>
        public static string Dialog_SyncthingBlockedByGroupPolicy_Message {
            get {
                return ResourceManager.GetString("Dialog_SyncthingBlockedByGroupPolicy_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error starting Syncthing.
        /// </summary>
        public static string Dialog_SyncthingBlockedByGroupPolicy_Title {
            get {
                return ResourceManager.GetString("Dialog_SyncthingBlockedByGroupPolicy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start Syncthing: {0}. Please see Syncthing&apos;s console output for clues..
        /// </summary>
        public static string Dialog_SyncthingDidNotStart_Message {
            get {
                return ResourceManager.GetString("Dialog_SyncthingDidNotStart_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing didn&apos;t start correctly.
        /// </summary>
        public static string Dialog_SyncthingDidNotStart_Title {
            get {
                return ResourceManager.GetString("Dialog_SyncthingDidNotStart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string FileTranfersTrayView_Header_Downloading {
            get {
                return ResourceManager.GetString("FileTranfersTrayView_Header_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (deleted).
        /// </summary>
        public static string FileTransfersTrayView_Deleted {
            get {
                return ResourceManager.GetString("FileTransfersTrayView_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0}/{1} ({2}/s).
        /// </summary>
        public static string FileTransfersTrayView_Downloading_RateKnown {
            get {
                return ResourceManager.GetString("FileTransfersTrayView_Downloading_RateKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0}/{1}.
        /// </summary>
        public static string FileTransfersTrayView_Downloading_RateUnknown {
            get {
                return ResourceManager.GetString("FileTransfersTrayView_Downloading_RateUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string FileTransfersTrayView_Error {
            get {
                return ResourceManager.GetString("FileTransfersTrayView_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Updated.
        /// </summary>
        public static string FileTransfersTrayView_Header_RecentlyUpdated {
            get {
                return ResourceManager.GetString("FileTransfersTrayView_Header_RecentlyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In: {0}/s.
        /// </summary>
        public static string FileTransfersTrayView_InConnectionRate {
            get {
                return ResourceManager.GetString("FileTransfersTrayView_InConnectionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recent file transfers.
        /// </summary>
        public static string FileTransfersTrayView_NothingToShow {
            get {
                return ResourceManager.GetString("FileTransfersTrayView_NothingToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out: {0}/s.
        /// </summary>
        public static string FileTransfersTrayView_OutConnectionRate {
            get {
                return ResourceManager.GetString("FileTransfersTrayView_OutConnectionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder: {0}
        ///Full Path: {1}.
        /// </summary>
        public static string FileTransfersTrayView_PathDetails {
            get {
                return ResourceManager.GetString("FileTransfersTrayView_PathDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        public static string Generic_Copy {
            get {
                return ResourceManager.GetString("Generic_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu_t.
        /// </summary>
        public static string Generic_Cut {
            get {
                return ResourceManager.GetString("Generic_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Generic_Dialog_Cancel {
            get {
                return ResourceManager.GetString("Generic_Dialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Generic_Dialog_Close {
            get {
                return ResourceManager.GetString("Generic_Dialog_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Generic_Dialog_No {
            get {
                return ResourceManager.GetString("Generic_Dialog_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Generic_Dialog_OK {
            get {
                return ResourceManager.GetString("Generic_Dialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Generic_Dialog_Save {
            get {
                return ResourceManager.GetString("Generic_Dialog_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Generic_Dialog_Yes {
            get {
                return ResourceManager.GetString("Generic_Dialog_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Paste.
        /// </summary>
        public static string Generic_Paste {
            get {
                return ResourceManager.GetString("Generic_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Remind Me Again.
        /// </summary>
        public static string NewVersionAlertView_Button_DontRemind {
            get {
                return ResourceManager.GetString("NewVersionAlertView_Button_DontRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Download Page.
        /// </summary>
        public static string NewVersionAlertView_Button_Download {
            get {
                return ResourceManager.GetString("NewVersionAlertView_Button_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Now.
        /// </summary>
        public static string NewVersionAlertView_Button_Install {
            get {
                return ResourceManager.GetString("NewVersionAlertView_Button_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind Me Later.
        /// </summary>
        public static string NewVersionAlertView_Button_RemindLater {
            get {
                return ResourceManager.GetString("NewVersionAlertView_Button_RemindLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog:.
        /// </summary>
        public static string NewVersionAlertView_Changelog {
            get {
                return ResourceManager.GetString("NewVersionAlertView_Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Don&apos;t Remind Me Again&apos; will silence reminders for this version. You can permanently disable new version alerts from the Settings page. Visit Help -&gt; About to manually check for a new version..
        /// </summary>
        public static string NewVersionAlertView_DontRemindMeExplanation {
            get {
                return ResourceManager.GetString("NewVersionAlertView_DontRemindMeExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor version {0} is available!.
        /// </summary>
        public static string NewVersionAlertView_NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAlertView_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor Update Available.
        /// </summary>
        public static string NewVersionAlertView_Title {
            get {
                return ResourceManager.GetString("NewVersionAlertView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Changelog.
        /// </summary>
        public static string NewVersionAlertView_ViewChangelog {
            get {
                return ResourceManager.GetString("NewVersionAlertView_ViewChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor version {0} was successfully installed..
        /// </summary>
        public static string NewVersionInstalledView_Message {
            get {
                return ResourceManager.GetString("NewVersionInstalledView_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor Updated.
        /// </summary>
        public static string NewVersionInstalledView_Title {
            get {
                return ResourceManager.GetString("NewVersionInstalledView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing Command-line Flags.
        /// </summary>
        public static string Settings_SyncthingCommandLineFlags {
            get {
                return ResourceManager.GetString("Settings_SyncthingCommandLineFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert if a new version of SyncTrayzor is available.
        /// </summary>
        public static string SettingsView_AlertOnNewVersion {
            get {
                return ResourceManager.GetString("SettingsView_AlertOnNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts are shown in a bar at the top of SyncTrayzor, and show a warning triangle on the tray icon..
        /// </summary>
        public static string SettingsView_Alerts_Description {
            get {
                return ResourceManager.GetString("SettingsView_Alerts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See the &apos;Folders&apos; tab for per-folder notification settings..
        /// </summary>
        public static string SettingsView_Alerts_SeeFolders {
            get {
                return ResourceManager.GetString("SettingsView_Alerts_SeeFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animate tray icon:.
        /// </summary>
        public static string SettingsView_AnimateTrayIcon {
            get {
                return ResourceManager.GetString("SettingsView_AnimateTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close to tray.
        /// </summary>
        public static string SettingsView_CloseToTray {
            get {
                return ResourceManager.GetString("SettingsView_CloseToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable hardware rendering.
        /// </summary>
        public static string SettingsView_DisableHardwareRendering {
            get {
                return ResourceManager.GetString("SettingsView_DisableHardwareRendering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert me of conflicted files.
        /// </summary>
        public static string SettingsView_EnableConflictFileMonitoring {
            get {
                return ResourceManager.GetString("SettingsView_EnableConflictFileMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert of failed file transfers.
        /// </summary>
        public static string SettingsView_EnableFailedTransferAlerts {
            get {
                return ResourceManager.GetString("SettingsView_EnableFailedTransferAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable different debug facilities in order to help debug problems. If you are asked to set STTRACE, please use this instead..
        /// </summary>
        public static string SettingsView_Logging_Explanation {
            get {
                return ResourceManager.GetString("SettingsView_Logging_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Level:.
        /// </summary>
        public static string SettingsView_Logging_LogLevel {
            get {
                return ResourceManager.GetString("SettingsView_Logging_LogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string SettingsView_Logging_LogLevel_Debug {
            get {
                return ResourceManager.GetString("SettingsView_Logging_LogLevel_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info (Default).
        /// </summary>
        public static string SettingsView_Logging_LogLevel_Info {
            get {
                return ResourceManager.GetString("SettingsView_Logging_LogLevel_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace.
        /// </summary>
        public static string SettingsView_Logging_LogLevel_Trace {
            get {
                return ResourceManager.GetString("SettingsView_Logging_LogLevel_Trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Syncthing Log File.
        /// </summary>
        public static string SettingsView_Logging_ShowSyncthingLog {
            get {
                return ResourceManager.GetString("SettingsView_Logging_ShowSyncthingLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show SyncTrayzor Log File.
        /// </summary>
        public static string SettingsView_Logging_ShowSyncTrayzorLog {
            get {
                return ResourceManager.GetString("SettingsView_Logging_ShowSyncTrayzorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing Debug Facilities unavailable. Please start Syncthing..
        /// </summary>
        public static string SettingsView_Logging_Unavailable {
            get {
                return ResourceManager.GetString("SettingsView_Logging_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause devices which connect over a metered network.
        /// </summary>
        public static string SettingsView_MeteredNetworks {
            get {
                return ResourceManager.GetString("SettingsView_MeteredNetworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be using Windows 8 or above to use this feature..
        /// </summary>
        public static string SettingsView_MeteredNetworks_NotSupported {
            get {
                return ResourceManager.GetString("SettingsView_MeteredNetworks_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to tray.
        /// </summary>
        public static string SettingsView_MinimizeToTray {
            get {
                return ResourceManager.GetString("SettingsView_MinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obfuscate device IDs in the log view.
        /// </summary>
        public static string SettingsView_ObfuscateDeviceIds {
            get {
                return ResourceManager.GetString("SettingsView_ObfuscateDeviceIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tray Icon only on close.
        /// </summary>
        public static string SettingsView_OnlyShowTrayIconOnClose {
            get {
                return ResourceManager.GetString("SettingsView_OnlyShowTrayIconOnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must restart Syncthing for these settings to take effect.
        ///
        ///Do you want to restart Syncthing now?.
        /// </summary>
        public static string SettingsView_RestartSyncthing_Message {
            get {
                return ResourceManager.GetString("SettingsView_RestartSyncthing_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Syncthing?.
        /// </summary>
        public static string SettingsView_RestartSyncthing_Title {
            get {
                return ResourceManager.GetString("SettingsView_RestartSyncthing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must restart SyncTrayzor for these settings to take effect.
        ///
        ///Do you want to restart SyncTrayzor now?.
        /// </summary>
        public static string SettingsView_RestartSyncTrayzor_Message {
            get {
                return ResourceManager.GetString("SettingsView_RestartSyncTrayzor_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart SyncTrayzor?.
        /// </summary>
        public static string SettingsView_RestartSyncTrayzor_Title {
            get {
                return ResourceManager.GetString("SettingsView_RestartSyncTrayzor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string SettingsView_Section_Advanced {
            get {
                return ResourceManager.GetString("SettingsView_Section_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        public static string SettingsView_Section_Alerts {
            get {
                return ResourceManager.GetString("SettingsView_Section_Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metered Networks.
        /// </summary>
        public static string SettingsView_Section_MeteredNetworks {
            get {
                return ResourceManager.GetString("SettingsView_Section_MeteredNetworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start on Login.
        /// </summary>
        public static string SettingsView_Section_StartOnLogin {
            get {
                return ResourceManager.GetString("SettingsView_Section_StartOnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing.
        /// </summary>
        public static string SettingsView_Section_Syncthing {
            get {
                return ResourceManager.GetString("SettingsView_Section_Syncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor.
        /// </summary>
        public static string SettingsView_Section_SyncTrayzor {
            get {
                return ResourceManager.GetString("SettingsView_Section_SyncTrayzor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray Icon.
        /// </summary>
        public static string SettingsView_Section_TrayIcon {
            get {
                return ResourceManager.GetString("SettingsView_Section_TrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &quot;Device Connected/Disconnected&quot; balloon messages.
        /// </summary>
        public static string SettingsView_ShowDeviceConnectivityBalloons {
            get {
                return ResourceManager.GetString("SettingsView_ShowDeviceConnectivityBalloons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &quot;Add New Device / Folder&quot; balloon messages.
        /// </summary>
        public static string SettingsView_ShowDeviceOrFolderRejectedBalloons {
            get {
                return ResourceManager.GetString("SettingsView_ShowDeviceOrFolderRejectedBalloons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &quot;Synchronized&quot; balloon messages even if no files were updated.
        /// </summary>
        public static string SettingsView_ShowSynchronizedBalloonIfNoFilesTransferred {
            get {
                return ResourceManager.GetString("SettingsView_ShowSynchronizedBalloonIfNoFilesTransferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Minimized.
        /// </summary>
        public static string SettingsView_StartMinimized {
            get {
                return ResourceManager.GetString("SettingsView_StartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically start on login.
        /// </summary>
        public static string SettingsView_StartOnLogin {
            get {
                return ResourceManager.GetString("SettingsView_StartOnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission denied. Please start SyncTrayzor as an Administrator to change these settings..
        /// </summary>
        public static string SettingsView_StartOnLogin_PermissionDenied {
            get {
                return ResourceManager.GetString("SettingsView_StartOnLogin_PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Syncthing when SyncTrayzor starts.
        /// </summary>
        public static string SettingsView_StartSyncthingAutomatically {
            get {
                return ResourceManager.GetString("SettingsView_StartSyncthingAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing Process Priority:.
        /// </summary>
        public static string SettingsView_Syncthing_ProcessPriority {
            get {
                return ResourceManager.GetString("SettingsView_Syncthing_ProcessPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above Normal.
        /// </summary>
        public static string SettingsView_Syncthing_ProcessPriority_AboveNormal {
            get {
                return ResourceManager.GetString("SettingsView_Syncthing_ProcessPriority_AboveNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below Normal.
        /// </summary>
        public static string SettingsView_Syncthing_ProcessPriority_BelowNormal {
            get {
                return ResourceManager.GetString("SettingsView_Syncthing_ProcessPriority_BelowNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string SettingsView_Syncthing_ProcessPriority_Idle {
            get {
                return ResourceManager.GetString("SettingsView_Syncthing_ProcessPriority_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string SettingsView_Syncthing_ProcessPriority_Normal {
            get {
                return ResourceManager.GetString("SettingsView_Syncthing_ProcessPriority_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUI Listen Address:.
        /// </summary>
        public static string SettingsView_SyncthingAddress {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor overrides the &quot;GUI Listen Address&quot; specified in Syncthing&apos;s configuration. However, you can set it to whatever value you like here..
        /// </summary>
        public static string SettingsView_SyncthingAddress_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingAddress_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing Custom Home Path:.
        /// </summary>
        public static string SettingsView_SyncthingCustomHomePath {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingCustomHomePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, overrides the default path for Syncthing&apos;s database and configuration.
        /// </summary>
        public static string SettingsView_SyncthingCustomHomePath_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingCustomHomePath_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Syncthing auto-upgrading.
        /// </summary>
        public static string SettingsView_SyncthingDenyUpgrade {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingDenyUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Syncthing from auto-upgrading. This is useful if a new version of Syncthing breaks compatibility with SyncTrayzor. You will need to downgrade the syncthing.exe file in SyncTrayzor&apos;s config folder.
        /// </summary>
        public static string SettingsView_SyncthingDenyUpgrade_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingDenyUpgrade_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing Environmental Variables:.
        /// </summary>
        public static string SettingsView_SyncthingEnvironmentalVariables {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingEnvironmentalVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string SettingsView_Tab_Folders {
            get {
                return ResourceManager.GetString("SettingsView_Tab_Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging + STTRACE.
        /// </summary>
        public static string SettingsView_Tab_Logging {
            get {
                return ResourceManager.GetString("SettingsView_Tab_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing.
        /// </summary>
        public static string SettingsView_Tab_Syncthing {
            get {
                return ResourceManager.GetString("SettingsView_Tab_Syncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor.
        /// </summary>
        public static string SettingsView_Tab_SyncTrayzor {
            get {
                return ResourceManager.GetString("SettingsView_Tab_SyncTrayzor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsView_Title {
            get {
                return ResourceManager.GetString("SettingsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any data transfer.
        /// </summary>
        public static string SettingsView_TrayIconAnimation_DataTransferring {
            get {
                return ResourceManager.GetString("SettingsView_TrayIconAnimation_DataTransferring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string SettingsView_TrayIconAnimation_Disabled {
            get {
                return ResourceManager.GetString("SettingsView_TrayIconAnimation_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing.
        /// </summary>
        public static string SettingsView_TrayIconAnimation_Syncing {
            get {
                return ResourceManager.GetString("SettingsView_TrayIconAnimation_Syncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use my computer&apos;s language, where available.
        /// </summary>
        public static string SettingsView_UseComputerCulture {
            get {
                return ResourceManager.GetString("SettingsView_UseComputerCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have the form &apos;host:port&apos;, e.g. &apos;localhost:8384&apos;.
        /// </summary>
        public static string SettingsView_Validation_InvalidUrl {
            get {
                return ResourceManager.GetString("SettingsView_Validation_InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should not be empty.
        /// </summary>
        public static string SettingsView_Validation_NotShouldBeEmpty {
            get {
                return ResourceManager.GetString("SettingsView_Validation_NotShouldBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set STTRACE in the &apos;Logging + STTRACE&apos; tab.
        /// </summary>
        public static string SettingsView_Validation_SetSttraceInTab {
            get {
                return ResourceManager.GetString("SettingsView_Validation_SetSttraceInTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not specify the flag {0}.
        /// </summary>
        public static string SettingsView_Validation_SyncthingCommandLineFlagIsNotAllowed {
            get {
                return ResourceManager.GetString("SettingsView_Validation_SyncthingCommandLineFlagIsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command-line flags must begin with &apos;-&apos;.
        /// </summary>
        public static string SettingsView_Validation_SyncthingCommandLineFlagsMustBeginWithHyphen {
            get {
                return ResourceManager.GetString("SettingsView_Validation_SyncthingCommandLineFlagsMustBeginWithHyphen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be in the format &apos;-flag&apos; or &apos;-flag=value&apos; or &apos;-flag=&quot;value with spaces&quot;&apos;.
        /// </summary>
        public static string SettingsView_Validation_SyncthingCommandLineFlagsMustHaveFormat {
            get {
                return ResourceManager.GetString("SettingsView_Validation_SyncthingCommandLineFlagsMustHaveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be in the format &apos;VAR=value&apos; or &apos;VAR=&quot;val1 val2&quot;&apos;.
        /// </summary>
        public static string SettingsView_Validation_SyncthingEnvironmentalVariablesMustHaveFormat {
            get {
                return ResourceManager.GetString("SettingsView_Validation_SyncthingEnvironmentalVariablesMustHaveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watched: The folder will be watched for changes, which means you can set a longer polling interval in Syncthing.
        ///
        ///Notifications: You will receive &apos;Synchronized&apos; balloon messages when files in this folder are updated..
        /// </summary>
        public static string SettingsView_WatchedFolders_Explanation {
            get {
                return ResourceManager.GetString("SettingsView_WatchedFolders_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string SettingsView_WatchedFolders_Header_Folder {
            get {
                return ResourceManager.GetString("SettingsView_WatchedFolders_Header_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string SettingsView_WatchedFolders_Header_Notifications {
            get {
                return ResourceManager.GetString("SettingsView_WatchedFolders_Header_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watched.
        /// </summary>
        public static string SettingsView_WatchedFolders_Header_Watched {
            get {
                return ResourceManager.GetString("SettingsView_WatchedFolders_Header_Watched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders unavailable. Please start Syncthing.
        /// </summary>
        public static string SettingsView_WatchedFolders_Unavailable {
            get {
                return ResourceManager.GetString("SettingsView_WatchedFolders_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string ShellView_Donate {
            get {
                return ResourceManager.GetString("ShellView_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string ShellView_Menu_File {
            get {
                return ResourceManager.GetString("ShellView_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Conflict Resolver.
        /// </summary>
        public static string ShellView_Menu_File_ConflictResolver {
            get {
                return ResourceManager.GetString("ShellView_Menu_File_ConflictResolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string ShellView_Menu_File_Exit {
            get {
                return ResourceManager.GetString("ShellView_Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string ShellView_Menu_File_Settings {
            get {
                return ResourceManager.GetString("ShellView_Menu_File_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string ShellView_Menu_Help {
            get {
                return ResourceManager.GetString("ShellView_Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string ShellView_Menu_Help_About {
            get {
                return ResourceManager.GetString("ShellView_Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Syncthing.
        /// </summary>
        public static string ShellView_Menu_Syncthing {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill _all Syncthing processes.
        /// </summary>
        public static string ShellView_Menu_Syncthing_KillAll {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_KillAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open in external browser.
        /// </summary>
        public static string ShellView_Menu_Syncthing_OpenExternal {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_OpenExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Refresh browser.
        /// </summary>
        public static string ShellView_Menu_Syncthing_Refresh {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R_estart.
        /// </summary>
        public static string ShellView_Menu_Syncthing_Restart {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Start.
        /// </summary>
        public static string ShellView_Menu_Syncthing_Start {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_top.
        /// </summary>
        public static string ShellView_Menu_Syncthing_Stop {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string ShellView_Menu_View {
            get {
                return ResourceManager.GetString("ShellView_Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing _Console.
        /// </summary>
        public static string ShellView_Menu_View_SyncthingConsole {
            get {
                return ResourceManager.GetString("ShellView_Menu_View_SyncthingConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Zoom Browser.
        /// </summary>
        public static string ShellView_Menu_Zoom {
            get {
                return ResourceManager.GetString("ShellView_Menu_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom _In.
        /// </summary>
        public static string ShellView_Menu_Zoom_In {
            get {
                return ResourceManager.GetString("ShellView_Menu_Zoom_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom _Out.
        /// </summary>
        public static string ShellView_Menu_Zoom_Out {
            get {
                return ResourceManager.GetString("ShellView_Menu_Zoom_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reset.
        /// </summary>
        public static string ShellView_Menu_Zoom_Reset {
            get {
                return ResourceManager.GetString("ShellView_Menu_Zoom_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentDescriptionLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentHomepageLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentHomepageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentLicenseLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentLicenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Text:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentLicenseTextLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentLicenseTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentNameLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentNotesLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentNotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor is built using many open-source components, and would not exist without them.
        ///Details on each component, and its license text, are shown below..
        /// </summary>
        public static string ThirdPartyComponentsView_Intro {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Party Components.
        /// </summary>
        public static string ThirdPartyComponentsView_Title {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:p:1 day|{} days} ago.
        /// </summary>
        public static string TimeAgo_Days {
            get {
                return ResourceManager.GetString("TimeAgo_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:p:1 hour|{} hours} ago.
        /// </summary>
        public static string TimeAgo_Hours {
            get {
                return ResourceManager.GetString("TimeAgo_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just now.
        /// </summary>
        public static string TimeAgo_JustNow {
            get {
                return ResourceManager.GetString("TimeAgo_JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:p:1 minute|{} minutes} ago.
        /// </summary>
        public static string TimeAgo_Minutes {
            get {
                return ResourceManager.GetString("TimeAgo_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:p:1 year|{} years} ago.
        /// </summary>
        public static string TimeAgo_Years {
            get {
                return ResourceManager.GetString("TimeAgo_Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;LANGUAGE&gt; translation by &lt;YOUR NAME&gt;.
        /// </summary>
        public static string TranslatorAttributation {
            get {
                return ResourceManager.GetString("TranslatorAttributation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} connected.
        /// </summary>
        public static string TrayIcon_Balloon_DeviceConnected_Message {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_DeviceConnected_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Connected.
        /// </summary>
        public static string TrayIcon_Balloon_DeviceConnected_Title {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_DeviceConnected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} disconnected.
        /// </summary>
        public static string TrayIcon_Balloon_DeviceDisconnected_Message {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_DeviceDisconnected_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Disconnected.
        /// </summary>
        public static string TrayIcon_Balloon_DeviceDisconnected_Title {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_DeviceDisconnected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device {0} ({1}) wants to connect. Open SyncTrayzor to add new device.
        /// </summary>
        public static string TrayIcon_Balloon_DeviceRejected_Message {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_DeviceRejected_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect device?.
        /// </summary>
        public static string TrayIcon_Balloon_DeviceRejected_Title {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_DeviceRejected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted {0:p:1 file|{} files}.
        /// </summary>
        public static string TrayIcon_Balloon_FinishedSyncing_DeletedFile {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_FinishedSyncing_DeletedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted {0:p:1 file|{} files} ({1:p:1 failure|{} failures}).
        /// </summary>
        public static string TrayIcon_Balloon_FinishedSyncing_DeletedFileWithFailures {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_FinishedSyncing_DeletedFileWithFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Deleted {1}.
        /// </summary>
        public static string TrayIcon_Balloon_FinishedSyncing_DeletedSingleFile {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_FinishedSyncing_DeletedSingleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Failed to delete {1} ({2}).
        /// </summary>
        public static string TrayIcon_Balloon_FinishedSyncing_FailedToDeleteSingleFile {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_FinishedSyncing_FailedToDeleteSingleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Failed to update {1} ({2}).
        /// </summary>
        public static string TrayIcon_Balloon_FinishedSyncing_FailedToUpdateSingleFile {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_FinishedSyncing_FailedToUpdateSingleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Finished Syncing.
        /// </summary>
        public static string TrayIcon_Balloon_FinishedSyncing_Message {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_FinishedSyncing_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1:l:{}|; }.
        /// </summary>
        public static string TrayIcon_Balloon_FinishedSyncing_Multiple {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_FinishedSyncing_Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Syncing.
        /// </summary>
        public static string TrayIcon_Balloon_FinishedSyncing_Title {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_FinishedSyncing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated {0:p:1 file|{} files}.
        /// </summary>
        public static string TrayIcon_Balloon_FinishedSyncing_UpdatedFile {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_FinishedSyncing_UpdatedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated {0:p:1 file|{} files} ({1:p:1 failure|{} failures}).
        /// </summary>
        public static string TrayIcon_Balloon_FinishedSyncing_UpdatedFileWithFailures {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_FinishedSyncing_UpdatedFileWithFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Updated {1}.
        /// </summary>
        public static string TrayIcon_Balloon_FinishedSyncing_UpdatedSingleFile {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_FinishedSyncing_UpdatedSingleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} wants to share folder {1}. Open SyncTrayzor to add new folder.
        /// </summary>
        public static string TrayIcon_Balloon_FolderRejected_Message {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_FolderRejected_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share folder?.
        /// </summary>
        public static string TrayIcon_Balloon_FolderRejected_Title {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_FolderRejected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close to Tray.
        /// </summary>
        public static string TrayIcon_Menu_CloseToTray {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_CloseToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string TrayIcon_Menu_Exit {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open _Folder.
        /// </summary>
        public static string TrayIcon_Menu_OpenFolder {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Restart Syncthing.
        /// </summary>
        public static string TrayIcon_Menu_RestartSyncthing {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_RestartSyncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open SyncTrayzor.
        /// </summary>
        public static string TrayIcon_Menu_Restore {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sett_ings.
        /// </summary>
        public static string TrayIcon_Menu_Settings {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Start Syncthing.
        /// </summary>
        public static string TrayIcon_Menu_StartSyncthing {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_StartSyncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_top Syncthing.
        /// </summary>
        public static string TrayIcon_Menu_StopSyncthing {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_StopSyncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something went badly wrong.
        ///SyncTrayzor is going to have to close. Sorry about that.
        /// </summary>
        public static string UnhandledExceptionView_IntroMessage {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_IntroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may be asked to provide a log file..
        /// </summary>
        public static string UnhandledExceptionView_LogFileLocation_Description {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_LogFileLocation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can find SyncTrayzor&apos;s log file here..
        /// </summary>
        public static string UnhandledExceptionView_LogFileLocation_Link {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_LogFileLocation_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and include the following information:.
        /// </summary>
        public static string UnhandledExceptionView_PleaseOpenIssue_Post {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_PleaseOpenIssue_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open an issue at.
        /// </summary>
        public static string UnhandledExceptionView_PleaseOpenIssue_Pre {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_PleaseOpenIssue_Pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string UnhandledExceptionView_Title {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string ViewerView_BrowseToFolder {
            get {
                return ResourceManager.GetString("ViewerView_BrowseToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string ViewerView_OpenFolder {
            get {
                return ResourceManager.GetString("ViewerView_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Syncthing.
        /// </summary>
        public static string ViewerView_StartSyncthing {
            get {
                return ResourceManager.GetString("ViewerView_StartSyncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing Starting....
        /// </summary>
        public static string ViewerView_SyncthingStarting {
            get {
                return ResourceManager.GetString("ViewerView_SyncthingStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing Stopped.
        /// </summary>
        public static string ViewerView_SyncthingStopped {
            get {
                return ResourceManager.GetString("ViewerView_SyncthingStopped", resourceCulture);
            }
        }
    }
}
