//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncTrayzor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/version-check")]
        public string UpdateApiUrl {
            get {
                return ((string)(this["UpdateApiUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://github.com/canton7/SyncTrayzor")]
        public string HomepageUrl {
            get {
                return ((string)(this["HomepageUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int DirectoryWatcherBackoffMilliseconds {
            get {
                return ((int)(this["DirectoryWatcherBackoffMilliseconds"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public int DirectoryWatcherFolderExistenceCheckMilliseconds {
            get {
                return ((int)(this["DirectoryWatcherFolderExistenceCheckMilliseconds"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://github.com/canton7/SyncTrayzor/issues")]
        public string IssuesUrl {
            get {
                return ((string)(this["IssuesUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableAutostartOnFirstStart {
            get {
                return ((bool)(this["EnableAutostartOnFirstStart"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CefRemoteDebuggingPort {
            get {
                return ((int)(this["CefRemoteDebuggingPort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("installed")]
        public string Variant {
            get {
                return ((string)(this["Variant"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
                    <Configuration xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
                        <ShowTrayIconOnlyOnClose>false</ShowTrayIconOnlyOnClose>
                        <MinimizeToTray>false</MinimizeToTray>
                        <CloseToTray>true</CloseToTray>
                        <ShowSynchronizedBalloon>true</ShowSynchronizedBalloon>
                        <ShowDeviceConnectivityBalloons>true</ShowDeviceConnectivityBalloons>
                        <SyncthingAddress>localhost:8384</SyncthingAddress>
                        <StartSyncthingAutomatically>true</StartSyncthingAutomatically>
                        <SyncthingUseCustomHome>true</SyncthingUseCustomHome>
                        <SyncthingDenyUpgrade>false</SyncthingDenyUpgrade>
                        <SyncthingRunLowPriority>false</SyncthingRunLowPriority>
                        <Folders />
                        <NotifyOfNewVersions>true</NotifyOfNewVersions>
                        <ObfuscateDeviceIDs>true</ObfuscateDeviceIDs>
                        <UseComputerCulture>true</UseComputerCulture>
                        <ShowSyncthingConsole>true</ShowSyncthingConsole>
                    </Configuration>
                ")]
        public global::SyncTrayzor.Services.Config.Configuration DefaultUserConfiguration {
            get {
                return ((global::SyncTrayzor.Services.Config.Configuration)(this["DefaultUserConfiguration"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
                    <PathConfiguration xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
                        <LogFilePath>%EXEPATH%\data\logs</LogFilePath>
                        <SyncthingCustomHomePath>%EXEPATH%\data\syncthing</SyncthingCustomHomePath>
                        <SyncthingPath>%EXEPATH%\syncthing.exe</SyncthingPath>
                        <ConfigurationFilePath>%EXEPATH%\data\config.xml</ConfigurationFilePath>
                    </PathConfiguration>
                ")]
        public global::SyncTrayzor.Services.Config.PathConfiguration PathConfiguration {
            get {
                return ((global::SyncTrayzor.Services.Config.PathConfiguration)(this["PathConfiguration"]));
            }
        }
    }
}
