//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncTrayzor.Properties.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_ca_ES_valencia {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ca_ES_valencia() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SyncTrayzor.Properties.Strings.Resources.ca-ES-valencia", typeof(Resources_ca_ES_valencia).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creat per Antony Male..
        /// </summary>
        public static string AboutView_CreatedByAuthor {
            get {
                return ResourceManager.GetString("AboutView_CreatedByAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrir pàgina de descàrrega.
        /// </summary>
        public static string AboutView_DownloadNewVersion {
            get {
                return ResourceManager.GetString("AboutView_DownloadNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova versió disponible: {0}.
        /// </summary>
        public static string AboutView_NewAppVersionAvailable {
            get {
                return ResourceManager.GetString("AboutView_NewAppVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desenvolupat baix llicència del MIT..
        /// </summary>
        public static string AboutView_ReleasedLicense {
            get {
                return ResourceManager.GetString("AboutView_ReleasedLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar llicències de Codi Obert (Open Source).
        /// </summary>
        public static string AboutView_ShowOtherLicenses {
            get {
                return ResourceManager.GetString("AboutView_ShowOtherLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versió de Syncthing: {0}.
        /// </summary>
        public static string AboutView_SyncthingVersion {
            get {
                return ResourceManager.GetString("AboutView_SyncthingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desconegut.
        /// </summary>
        public static string AboutView_UnknownVersion {
            get {
                return ResourceManager.GetString("AboutView_UnknownVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versió: {0}.
        /// </summary>
        public static string AboutView_Version {
            get {
                return ResourceManager.GetString("AboutView_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Està segur de que vol matar tots el procesos de Syncthing, inclús els que no són gestionats per SyncTrayzor?.
        /// </summary>
        public static string Dialog_ConfirmKillAllProcesses_Message {
            get {
                return ResourceManager.GetString("Dialog_ConfirmKillAllProcesses_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Està segur?.
        /// </summary>
        public static string Dialog_ConfirmKillAllProcesses_Title {
            get {
                return ResourceManager.GetString("Dialog_ConfirmKillAllProcesses_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No s&apos;ha pogut iniciar Syncthing.
        ///
        ///Per favor, revise el registre per a determinar la causa.
        ///
        ///Si apareix &quot;FATAL: No es pot obrir la base de dades&quot; (&quot;FATAL: Cannot open database&quot;), per favor, tanque totes les instàncies obertes de Syncthing. Si SyncTrayzor ja havia fallat previament, poden haver encara procesos zombie vius. Per favor, utilitze la opció de menú &quot;Syncthing -&gt; Matar tots els procesos de Syncthing&quot; per a parar-los. A continuació, utilitze &quot;Syncthing -&gt; Iniciar&quot; per a iniciar Syncthing altra vegada [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Dialog_FailedToStartSyncthing_Message {
            get {
                return ResourceManager.GetString("Dialog_FailedToStartSyncthing_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing ha fallat al iniciar.
        /// </summary>
        public static string Dialog_FailedToStartSyncthing_Title {
            get {
                return ResourceManager.GetString("Dialog_FailedToStartSyncthing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No s&apos;ha pogut iniciar Syncthing: {0}
        ///
        ///Podria ser perquè Windows està configurat per a prohibir l&apos;execució de fitxers en la carpeta AppData o perquè té instal·lat un anti-malware (per exemple CryptoPrevent ) que no permet executar fitxers dins de la carpeta AppData.
        ///
        ///Per favor, canvie els ajustos / llistes blanques per a permetre l&apos;execució de &apos;{1}&apos;..
        /// </summary>
        public static string Dialog_SyncthingBlockedByGroupPolicy_Message {
            get {
                return ResourceManager.GetString("Dialog_SyncthingBlockedByGroupPolicy_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error iniciant Syncthing.
        /// </summary>
        public static string Dialog_SyncthingBlockedByGroupPolicy_Title {
            get {
                return ResourceManager.GetString("Dialog_SyncthingBlockedByGroupPolicy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start Syncthing: {0}. Please see Syncthing&apos;s console output for clues..
        /// </summary>
        public static string Dialog_SyncthingDidNotStart_Message {
            get {
                return ResourceManager.GetString("Dialog_SyncthingDidNotStart_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing didn&apos;t start correctly.
        /// </summary>
        public static string Dialog_SyncthingDidNotStart_Title {
            get {
                return ResourceManager.GetString("Dialog_SyncthingDidNotStart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string FileTranfersTrayView_Header_Downloading {
            get {
                return ResourceManager.GetString("FileTranfersTrayView_Header_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (deleted).
        /// </summary>
        public static string FileTransfersTrayView_Deleted {
            get {
                return ResourceManager.GetString("FileTransfersTrayView_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0}/{1} ({2}/s).
        /// </summary>
        public static string FileTransfersTrayView_Downloading_RateKnown {
            get {
                return ResourceManager.GetString("FileTransfersTrayView_Downloading_RateKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0}/{1}.
        /// </summary>
        public static string FileTransfersTrayView_Downloading_RateUnknown {
            get {
                return ResourceManager.GetString("FileTransfersTrayView_Downloading_RateUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string FileTransfersTrayView_Error {
            get {
                return ResourceManager.GetString("FileTransfersTrayView_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Updated.
        /// </summary>
        public static string FileTransfersTrayView_Header_RecentlyUpdated {
            get {
                return ResourceManager.GetString("FileTransfersTrayView_Header_RecentlyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In: {0}/s.
        /// </summary>
        public static string FileTransfersTrayView_InConnectionRate {
            get {
                return ResourceManager.GetString("FileTransfersTrayView_InConnectionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recent file transfers.
        /// </summary>
        public static string FileTransfersTrayView_NothingToShow {
            get {
                return ResourceManager.GetString("FileTransfersTrayView_NothingToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out: {0}/s.
        /// </summary>
        public static string FileTransfersTrayView_OutConnectionRate {
            get {
                return ResourceManager.GetString("FileTransfersTrayView_OutConnectionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        public static string FileTransfersTrayView_Starting {
            get {
                return ResourceManager.GetString("FileTransfersTrayView_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        public static string Generic_Copy {
            get {
                return ResourceManager.GetString("Generic_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu_t.
        /// </summary>
        public static string Generic_Cut {
            get {
                return ResourceManager.GetString("Generic_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel·lar.
        /// </summary>
        public static string Generic_Dialog_Cancel {
            get {
                return ResourceManager.GetString("Generic_Dialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tancar.
        /// </summary>
        public static string Generic_Dialog_Close {
            get {
                return ResourceManager.GetString("Generic_Dialog_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Generic_Dialog_No {
            get {
                return ResourceManager.GetString("Generic_Dialog_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Generic_Dialog_OK {
            get {
                return ResourceManager.GetString("Generic_Dialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Generic_Dialog_Save {
            get {
                return ResourceManager.GetString("Generic_Dialog_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí.
        /// </summary>
        public static string Generic_Dialog_Yes {
            get {
                return ResourceManager.GetString("Generic_Dialog_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Paste.
        /// </summary>
        public static string Generic_Paste {
            get {
                return ResourceManager.GetString("Generic_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recordar-m&apos;ho de nou.
        /// </summary>
        public static string NewVersionAlertView_Button_DontRemind {
            get {
                return ResourceManager.GetString("NewVersionAlertView_Button_DontRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrir pàgina de descàrrega.
        /// </summary>
        public static string NewVersionAlertView_Button_Download {
            get {
                return ResourceManager.GetString("NewVersionAlertView_Button_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instal·lar ara.
        /// </summary>
        public static string NewVersionAlertView_Button_Install {
            get {
                return ResourceManager.GetString("NewVersionAlertView_Button_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordar-m&apos;ho més tard.
        /// </summary>
        public static string NewVersionAlertView_Button_RemindLater {
            get {
                return ResourceManager.GetString("NewVersionAlertView_Button_RemindLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registre de canvis:.
        /// </summary>
        public static string NewVersionAlertView_Changelog {
            get {
                return ResourceManager.GetString("NewVersionAlertView_Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;No recordar-m&apos;ho de nou&quot; sil•lenciarà els recordatoris per aquesta versió. Els avisos de nova versió es poden desactivar des-de la pàgina de Configuració. Entrant en Ajuda -&gt; Sobre es pot comprovar manualment si hi ha una nova versió..
        /// </summary>
        public static string NewVersionAlertView_DontRemindMeExplanation {
            get {
                return ResourceManager.GetString("NewVersionAlertView_DontRemindMeExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponible la versió {0} de SyncTrayzor!.
        /// </summary>
        public static string NewVersionAlertView_NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAlertView_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponible una actualització de SyncTrayzor .
        /// </summary>
        public static string NewVersionAlertView_Title {
            get {
                return ResourceManager.GetString("NewVersionAlertView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vore el llistat de canvis.
        /// </summary>
        public static string NewVersionAlertView_ViewChangelog {
            get {
                return ResourceManager.GetString("NewVersionAlertView_ViewChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La versió {0} de SyncTrayzor es va instal·lar amb èxit..
        /// </summary>
        public static string NewVersionInstalledView_Message {
            get {
                return ResourceManager.GetString("NewVersionInstalledView_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor actualitzat.
        /// </summary>
        public static string NewVersionInstalledView_Title {
            get {
                return ResourceManager.GetString("NewVersionInstalledView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avisar si hi ha disponible una nova versió de SyncTrayzor.
        /// </summary>
        public static string SettingsView_AlertOnNewVersion {
            get {
                return ResourceManager.GetString("SettingsView_AlertOnNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clau del API:.
        /// </summary>
        public static string SettingsView_ApiKey {
            get {
                return ResourceManager.GetString("SettingsView_ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor sobrescriu la clau de l&apos;API especificada en la configuració de Syncthing. En qualsevol cas, es pot adjustar ací al valor desitjat..
        /// </summary>
        public static string SettingsView_ApiKey_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_ApiKey_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tancar a l&apos;àrea de notificacions.
        /// </summary>
        public static string SettingsView_CloseToTray {
            get {
                return ResourceManager.GetString("SettingsView_CloseToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimitzar a l&apos;àrea de notificacions.
        /// </summary>
        public static string SettingsView_MinimizeToTray {
            get {
                return ResourceManager.GetString("SettingsView_MinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to És necessari reiniciar Syncthing per a que els canvis en aquestos ajustos es facen efectius..
        /// </summary>
        public static string SettingsView_MustRestartSyncthingWarning {
            get {
                return ResourceManager.GetString("SettingsView_MustRestartSyncthingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofuscar la ID del dispositiu en la vista del registre.
        /// </summary>
        public static string SettingsView_ObfuscateDeviceIds {
            get {
                return ResourceManager.GetString("SettingsView_ObfuscateDeviceIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar solament l&apos;icona de l&apos;àrea de notificacions al tancar.
        /// </summary>
        public static string SettingsView_OnlyShowTrayIconOnClose {
            get {
                return ResourceManager.GetString("SettingsView_OnlyShowTrayIconOnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avançat.
        /// </summary>
        public static string SettingsView_Section_Advanced {
            get {
                return ResourceManager.GetString("SettingsView_Section_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar al fer Login.
        /// </summary>
        public static string SettingsView_Section_StartOnLogin {
            get {
                return ResourceManager.GetString("SettingsView_Section_StartOnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing.
        /// </summary>
        public static string SettingsView_Section_Syncthing {
            get {
                return ResourceManager.GetString("SettingsView_Section_Syncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor.
        /// </summary>
        public static string SettingsView_Section_SyncTrayzor {
            get {
                return ResourceManager.GetString("SettingsView_Section_SyncTrayzor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icona de l&apos;àrea de notificacions.
        /// </summary>
        public static string SettingsView_Section_TrayIcon {
            get {
                return ResourceManager.GetString("SettingsView_Section_TrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpetes observades.
        /// </summary>
        public static string SettingsView_Section_WatchedFolders {
            get {
                return ResourceManager.GetString("SettingsView_Section_WatchedFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar els missatges de &quot;Sincronitzat&quot;.
        /// </summary>
        public static string SettingsView_ShowBalloonWhenSynchronized {
            get {
                return ResourceManager.GetString("SettingsView_ShowBalloonWhenSynchronized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar els missatges emergents de dispositiu Connectat/Desconnectat.
        /// </summary>
        public static string SettingsView_ShowDeviceConnectivityBalloons {
            get {
                return ResourceManager.GetString("SettingsView_ShowDeviceConnectivityBalloons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar minimitzat.
        /// </summary>
        public static string SettingsView_StartMinimized {
            get {
                return ResourceManager.GetString("SettingsView_StartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Començar automàticament al fer login.
        /// </summary>
        public static string SettingsView_StartOnLogin {
            get {
                return ResourceManager.GetString("SettingsView_StartOnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permís denegat. Per favor, arranque SyncTrayzor com Administrador per a poder canviar aquestos ajustos..
        /// </summary>
        public static string SettingsView_StartOnLogin_PermissionDenied {
            get {
                return ResourceManager.GetString("SettingsView_StartOnLogin_PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Syncthing al mateix temps que SyncTrayzor.
        /// </summary>
        public static string SettingsView_StartSyncthingAutomatically {
            get {
                return ResourceManager.GetString("SettingsView_StartSyncthingAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direcció d&apos;escolta de l&apos;Interfície Gràfic d&apos;Usuari (GUI):.
        /// </summary>
        public static string SettingsView_SyncthingAddress {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor sobreescriu la &quot;Direcció d&apos;escolta de l&apos;Interfície Gràfica d&apos;Usuari (GUI)&quot; especificada a la configuració de Syncthing. De qualsevol forma, es pot introduïr ací el valor que es dessitje..
        /// </summary>
        public static string SettingsView_SyncthingAddress_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingAddress_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parar l&apos;auto actualització de Syncthing.
        /// </summary>
        public static string SettingsView_SyncthingDenyUpgrade {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingDenyUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parar l&apos;auto actualització de Syncthing. Açò pot ser útil quant una nova versió de Syncthing trenque la compatibilitat amb SyncTrayzor. Serà necessari tornar a una versió anterior de syncthing.exe en la carpeta de configuració de SyncTrayzor..
        /// </summary>
        public static string SettingsView_SyncthingDenyUpgrade_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingDenyUpgrade_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables d&apos;entorn de Syncthing.
        /// </summary>
        public static string SettingsView_SyncthingEnvironmentalVariables {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingEnvironmentalVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executar Syncthing com un procés de baixa prioritat.
        /// </summary>
        public static string SettingsView_SyncthingRunLowPriority {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingRunLowPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Syncthing&apos;s default database location.
        /// </summary>
        public static string SettingsView_SyncthingUseDefaultHome {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingUseDefaultHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If unchecked, this will mean that SyncTrayzor will see a different set of configured folders to any other Syncthing instances on your computer..
        /// </summary>
        public static string SettingsView_SyncthingUseDefaultHome_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingUseDefaultHome_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing.
        /// </summary>
        public static string SettingsView_Tab_Syncthing {
            get {
                return ResourceManager.GetString("SettingsView_Tab_Syncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor.
        /// </summary>
        public static string SettingsView_Tab_SyncTrayzor {
            get {
                return ResourceManager.GetString("SettingsView_Tab_SyncTrayzor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajustos.
        /// </summary>
        public static string SettingsView_Title {
            get {
                return ResourceManager.GetString("SettingsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilitzar el llenguatge de l&apos;ordinador, quant siga possible. Serà necessari reiniciar SyncTrayzor per a que aquest canvi es faça efectiu..
        /// </summary>
        public static string SettingsView_UseComputerCulture {
            get {
                return ResourceManager.GetString("SettingsView_UseComputerCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deu ser una URL vàlida.
        /// </summary>
        public static string SettingsView_Validation_InvalidUrl {
            get {
                return ResourceManager.GetString("SettingsView_Validation_InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No deu estar buit.
        /// </summary>
        public static string SettingsView_Validation_NotShouldBeEmpty {
            get {
                return ResourceManager.GetString("SettingsView_Validation_NotShouldBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deu mantindre el format &apos;VAR=value VAR2=&quot;val1 val2&quot;&apos;.
        /// </summary>
        public static string SettingsView_Validation_SyncthingEnvironmentalVariablesMustHaveFormat {
            get {
                return ResourceManager.GetString("SettingsView_Validation_SyncthingEnvironmentalVariablesMustHaveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les següents carpetes seràn vigilades per si canvien, el que vol dir que pot establir un interval de comprovació més llarg..
        /// </summary>
        public static string SettingsView_WatchedFolders_Explanation {
            get {
                return ResourceManager.GetString("SettingsView_WatchedFolders_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpetes no disponibles. Per favor, inicie Syncthing.
        /// </summary>
        public static string SettingsView_WatchedFolders_Unavailable {
            get {
                return ResourceManager.GetString("SettingsView_WatchedFolders_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Fitxer.
        /// </summary>
        public static string ShellView_Menu_File {
            get {
                return ResourceManager.GetString("ShellView_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Eixir.
        /// </summary>
        public static string ShellView_Menu_File_Exit {
            get {
                return ResourceManager.GetString("ShellView_Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Configuració.
        /// </summary>
        public static string ShellView_Menu_File_Settings {
            get {
                return ResourceManager.GetString("ShellView_Menu_File_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ajuda.
        /// </summary>
        public static string ShellView_Menu_Help {
            get {
                return ResourceManager.GetString("ShellView_Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Sobre.
        /// </summary>
        public static string ShellView_Menu_Help_About {
            get {
                return ResourceManager.GetString("ShellView_Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Syncthing.
        /// </summary>
        public static string ShellView_Menu_Syncthing {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Matar.
        /// </summary>
        public static string ShellView_Menu_Syncthing_Kill {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_Kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matar _tots els processos de Syncthing.
        /// </summary>
        public static string ShellView_Menu_Syncthing_KillAll {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_KillAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Obrir en navegador extern.
        /// </summary>
        public static string ShellView_Menu_Syncthing_OpenExternal {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_OpenExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Refrescar el navegador.
        /// </summary>
        public static string ShellView_Menu_Syncthing_Refresh {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R_einiciar.
        /// </summary>
        public static string ShellView_Menu_Syncthing_Restart {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Començar.
        /// </summary>
        public static string ShellView_Menu_Syncthing_Start {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P_arar.
        /// </summary>
        public static string ShellView_Menu_Syncthing_Stop {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Vista.
        /// </summary>
        public static string ShellView_Menu_View {
            get {
                return ResourceManager.GetString("ShellView_Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consola de Syncthing.
        /// </summary>
        public static string ShellView_Menu_View_SyncthingConsole {
            get {
                return ResourceManager.GetString("ShellView_Menu_View_SyncthingConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector de zoom.
        /// </summary>
        public static string ShellView_Menu_Zoom {
            get {
                return ResourceManager.GetString("ShellView_Menu_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acostar zoom.
        /// </summary>
        public static string ShellView_Menu_Zoom_In {
            get {
                return ResourceManager.GetString("ShellView_Menu_Zoom_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allunyar zoom.
        /// </summary>
        public static string ShellView_Menu_Zoom_Out {
            get {
                return ResourceManager.GetString("ShellView_Menu_Zoom_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Resetejar.
        /// </summary>
        public static string ShellView_Menu_Zoom_Reset {
            get {
                return ResourceManager.GetString("ShellView_Menu_Zoom_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripció:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentDescriptionLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pàgina d&apos;inici:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentHomepageLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentHomepageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llicència:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentLicenseLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentLicenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text de llicència:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentLicenseTextLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentLicenseTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentNameLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentNotesLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentNotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor s&apos;ha construït amb molts components open-source i no existiria sense ells..
        ///Més davall es poden trovar els detalls de cada component i el seu text de llicència..
        /// </summary>
        public static string ThirdPartyComponentsView_Intro {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components d&apos;un tercer.
        /// </summary>
        public static string ThirdPartyComponentsView_Title {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        public static string TimeAgo_Days_Plural {
            get {
                return ResourceManager.GetString("TimeAgo_Days_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day ago.
        /// </summary>
        public static string TimeAgo_Days_Singular {
            get {
                return ResourceManager.GetString("TimeAgo_Days_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string TimeAgo_Hours_Plural {
            get {
                return ResourceManager.GetString("TimeAgo_Hours_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour ago.
        /// </summary>
        public static string TimeAgo_Hours_Singular {
            get {
                return ResourceManager.GetString("TimeAgo_Hours_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just now.
        /// </summary>
        public static string TimeAgo_JustNow {
            get {
                return ResourceManager.GetString("TimeAgo_JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        public static string TimeAgo_Minutes_Plural {
            get {
                return ResourceManager.GetString("TimeAgo_Minutes_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 minute ago.
        /// </summary>
        public static string TimeAgo_Minutes_Singular {
            get {
                return ResourceManager.GetString("TimeAgo_Minutes_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years ago.
        /// </summary>
        public static string TimeAgo_Years_Plural {
            get {
                return ResourceManager.GetString("TimeAgo_Years_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 year ago.
        /// </summary>
        public static string TimeAgo_Years_Singular {
            get {
                return ResourceManager.GetString("TimeAgo_Years_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valencian translation by Carlos de Andrés.
        /// </summary>
        public static string TranslatorAttributation {
            get {
                return ResourceManager.GetString("TranslatorAttributation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} connectat.
        /// </summary>
        public static string TrayIcon_Balloon_DeviceConnected_Message {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_DeviceConnected_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositiu connectat.
        /// </summary>
        public static string TrayIcon_Balloon_DeviceConnected_Title {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_DeviceConnected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} desconnectat.
        /// </summary>
        public static string TrayIcon_Balloon_DeviceDisconnected_Message {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_DeviceDisconnected_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositiu desconnectat.
        /// </summary>
        public static string TrayIcon_Balloon_DeviceDisconnected_Title {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_DeviceDisconnected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Sincronització finalitzada.
        /// </summary>
        public static string TrayIcon_Balloon_FinishedSyncing_Message {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_FinishedSyncing_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincronització finalitzada.
        /// </summary>
        public static string TrayIcon_Balloon_FinishedSyncing_Title {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_FinishedSyncing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tancar a l&apos;àrea de notificació.
        /// </summary>
        public static string TrayIcon_Menu_CloseToTray {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_CloseToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Eixir.
        /// </summary>
        public static string TrayIcon_Menu_Exit {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Obrir carpeta.
        /// </summary>
        public static string TrayIcon_Menu_OpenFolder {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R_einiciar Syncthing.
        /// </summary>
        public static string TrayIcon_Menu_RestartSyncthing {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_RestartSyncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Restaurar.
        /// </summary>
        public static string TrayIcon_Menu_Restore {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajustos.
        /// </summary>
        public static string TrayIcon_Menu_Settings {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Iniciar Syncthing.
        /// </summary>
        public static string TrayIcon_Menu_StartSyncthing {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_StartSyncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parar Syncthing.
        /// </summary>
        public static string TrayIcon_Menu_StopSyncthing {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_StopSyncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ups! Alguna cosa ha anat molt malament!.
        ///SyncTrayzor va a tindre que tancar-se. Disculpe les molèsties..
        /// </summary>
        public static string UnhandledExceptionView_IntroMessage {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_IntroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UnhandledExceptionView_LogFileLocation_Post {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_LogFileLocation_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potser que se li demane proporcionar un fitxer de registre. El pot trovar a:.
        /// </summary>
        public static string UnhandledExceptionView_LogFileLocation_Pre {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_LogFileLocation_Pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e inclou la següent informació:.
        /// </summary>
        public static string UnhandledExceptionView_PleaseOpenIssue_Post {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_PleaseOpenIssue_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per favor, pot obrir una incidència a.
        /// </summary>
        public static string UnhandledExceptionView_PleaseOpenIssue_Pre {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_PleaseOpenIssue_Pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string UnhandledExceptionView_Title {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrir carpeta.
        /// </summary>
        public static string ViewerView_OpenFolder {
            get {
                return ResourceManager.GetString("ViewerView_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Syncthing.
        /// </summary>
        public static string ViewerView_StartSyncthing {
            get {
                return ResourceManager.GetString("ViewerView_StartSyncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciant Syncthing....
        /// </summary>
        public static string ViewerView_SyncthingStarting {
            get {
                return ResourceManager.GetString("ViewerView_SyncthingStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing detingut.
        /// </summary>
        public static string ViewerView_SyncthingStopped {
            get {
                return ResourceManager.GetString("ViewerView_SyncthingStopped", resourceCulture);
            }
        }
    }
}
