//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncTrayzor.Properties.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SyncTrayzor.Properties.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Antony Male..
        /// </summary>
        public static string AboutView_CreatedByAuthor {
            get {
                return ResourceManager.GetString("AboutView_CreatedByAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string AboutView_DownloadNewVersion {
            get {
                return ResourceManager.GetString("AboutView_DownloadNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available: {0}.
        /// </summary>
        public static string AboutView_NewAppVersionAvailable {
            get {
                return ResourceManager.GetString("AboutView_NewAppVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released under the MIT license..
        /// </summary>
        public static string AboutView_ReleasedLicense {
            get {
                return ResourceManager.GetString("AboutView_ReleasedLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Open Source Licenses.
        /// </summary>
        public static string AboutView_ShowOtherLicenses {
            get {
                return ResourceManager.GetString("AboutView_ShowOtherLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing Version: {0}.
        /// </summary>
        public static string AboutView_SyncthingVersion {
            get {
                return ResourceManager.GetString("AboutView_SyncthingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string AboutView_UnknownVersion {
            get {
                return ResourceManager.GetString("AboutView_UnknownVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string AboutView_Version {
            get {
                return ResourceManager.GetString("AboutView_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to kill all Syncthing processes, even those not managed by SyncTrayzor?.
        /// </summary>
        public static string Dialog_ConfirmKillAllProcesses_Message {
            get {
                return ResourceManager.GetString("Dialog_ConfirmKillAllProcesses_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really?.
        /// </summary>
        public static string Dialog_ConfirmKillAllProcesses_Title {
            get {
                return ResourceManager.GetString("Dialog_ConfirmKillAllProcesses_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start Syncthing.
        ///
        ///Please read the log to determine the cause.
        ///
        ///If &quot;FATAL: Cannot open database&quot; appears, please close any other open instances of Syncthing. If SyncTrayzor crashed previously, there may still be zombine Syncthing processes alive. Please use the menu option &quot;Syncthing -&gt; Kill all Syncthing processes&quot; to stop them, then use &quot;Syncthing -&gt; Start&quot; to start Syncthing again..
        /// </summary>
        public static string Dialog_FailedToStartSyncthing_Message {
            get {
                return ResourceManager.GetString("Dialog_FailedToStartSyncthing_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing failed to start.
        /// </summary>
        public static string Dialog_FailedToStartSyncthing_Title {
            get {
                return ResourceManager.GetString("Dialog_FailedToStartSyncthing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start Syncthing: {0}
        ///
        ///This could be because Windows if set up to forbid executing files in AppData, or because you have anti-malware installed (e.g. CryptoPrevent ) which prevents executing files in AppData.
        ///
        ///Please adjust your settings / whitelists to allow &apos;{1}&apos; to execute.
        /// </summary>
        public static string Dialog_SyncthingBlockedByGroupPolicy_Message {
            get {
                return ResourceManager.GetString("Dialog_SyncthingBlockedByGroupPolicy_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error starting Syncthing.
        /// </summary>
        public static string Dialog_SyncthingBlockedByGroupPolicy_Title {
            get {
                return ResourceManager.GetString("Dialog_SyncthingBlockedByGroupPolicy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Generic_Dialog_Cancel {
            get {
                return ResourceManager.GetString("Generic_Dialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Generic_Dialog_Close {
            get {
                return ResourceManager.GetString("Generic_Dialog_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Generic_Dialog_No {
            get {
                return ResourceManager.GetString("Generic_Dialog_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Generic_Dialog_OK {
            get {
                return ResourceManager.GetString("Generic_Dialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Generic_Dialog_Save {
            get {
                return ResourceManager.GetString("Generic_Dialog_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Generic_Dialog_Yes {
            get {
                return ResourceManager.GetString("Generic_Dialog_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Remind Me Again.
        /// </summary>
        public static string NewVersionAlertView_Button_DontRemind {
            get {
                return ResourceManager.GetString("NewVersionAlertView_Button_DontRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Now.
        /// </summary>
        public static string NewVersionAlertView_Button_Download {
            get {
                return ResourceManager.GetString("NewVersionAlertView_Button_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind Me Later.
        /// </summary>
        public static string NewVersionAlertView_Button_RemindLater {
            get {
                return ResourceManager.GetString("NewVersionAlertView_Button_RemindLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog:.
        /// </summary>
        public static string NewVersionAlertView_Changelog {
            get {
                return ResourceManager.GetString("NewVersionAlertView_Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Don&apos;t Remind Me Again&apos; will silence reminders for this version. You can permanently disable new version alerts from the Settings page. Visit Help -&gt; About to manually check for a new version..
        /// </summary>
        public static string NewVersionAlertView_DontRemindMeExplanation {
            get {
                return ResourceManager.GetString("NewVersionAlertView_DontRemindMeExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of SyncTrayzor is available!
        ///
        ///Version: {0}
        ///
        ///Do you want to download it now?.
        /// </summary>
        public static string NewVersionAlertView_NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAlertView_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor Update Available.
        /// </summary>
        public static string NewVersionAlertView_Title {
            get {
                return ResourceManager.GetString("NewVersionAlertView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert if a new version of SyncTrayzor is available.
        /// </summary>
        public static string SettingsView_AlertOnNewVersion {
            get {
                return ResourceManager.GetString("SettingsView_AlertOnNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key:.
        /// </summary>
        public static string SettingsView_ApiKey {
            get {
                return ResourceManager.GetString("SettingsView_ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor overrides the API key specified in Syncthing&apos;s configuration. However, you can set it to whatever value you like here..
        /// </summary>
        public static string SettingsView_ApiKey_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_ApiKey_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close to tray.
        /// </summary>
        public static string SettingsView_CloseToTray {
            get {
                return ResourceManager.GetString("SettingsView_CloseToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to tray.
        /// </summary>
        public static string SettingsView_MinimizeToTray {
            get {
                return ResourceManager.GetString("SettingsView_MinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must restart Syncthing for changes in these settings to take effect.
        /// </summary>
        public static string SettingsView_MustRestartSyncthingWarning {
            get {
                return ResourceManager.GetString("SettingsView_MustRestartSyncthingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obfuscate device IDs in the log view.
        /// </summary>
        public static string SettingsView_ObfuscateDeviceIds {
            get {
                return ResourceManager.GetString("SettingsView_ObfuscateDeviceIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tray Icon only on close.
        /// </summary>
        public static string SettingsView_OnlyShowTrayIconOnClose {
            get {
                return ResourceManager.GetString("SettingsView_OnlyShowTrayIconOnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string SettingsView_Section_Advanced {
            get {
                return ResourceManager.GetString("SettingsView_Section_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start on Login.
        /// </summary>
        public static string SettingsView_Section_StartOnLogin {
            get {
                return ResourceManager.GetString("SettingsView_Section_StartOnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing.
        /// </summary>
        public static string SettingsView_Section_Syncthing {
            get {
                return ResourceManager.GetString("SettingsView_Section_Syncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor.
        /// </summary>
        public static string SettingsView_Section_SyncTrayzor {
            get {
                return ResourceManager.GetString("SettingsView_Section_SyncTrayzor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray Icon.
        /// </summary>
        public static string SettingsView_Section_TrayIcon {
            get {
                return ResourceManager.GetString("SettingsView_Section_TrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watched Folders.
        /// </summary>
        public static string SettingsView_Section_WatchedFolders {
            get {
                return ResourceManager.GetString("SettingsView_Section_WatchedFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &apos;Synchronized&apos; balloon messages.
        /// </summary>
        public static string SettingsView_ShowBalloonWhenSynchronized {
            get {
                return ResourceManager.GetString("SettingsView_ShowBalloonWhenSynchronized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show device Connected/Disconnected balloon messages.
        /// </summary>
        public static string SettingsView_ShowDeviceConnectivityBalloons {
            get {
                return ResourceManager.GetString("SettingsView_ShowDeviceConnectivityBalloons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Minimized.
        /// </summary>
        public static string SettingsView_StartMinimized {
            get {
                return ResourceManager.GetString("SettingsView_StartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically start on login.
        /// </summary>
        public static string SettingsView_StartOnLogin {
            get {
                return ResourceManager.GetString("SettingsView_StartOnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission denied. Please start SyncTrayzor as an Administrator to change these settings..
        /// </summary>
        public static string SettingsView_StartOnLogin_PermissionDenied {
            get {
                return ResourceManager.GetString("SettingsView_StartOnLogin_PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Syncthing when SyncTrayzor starts.
        /// </summary>
        public static string SettingsView_StartSyncthingAutomatically {
            get {
                return ResourceManager.GetString("SettingsView_StartSyncthingAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUI Listen Address:.
        /// </summary>
        public static string SettingsView_SyncthingAddress {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor overrides the &quot;GUI Listen Address&quot; specified in Syncthing&apos;s configuration. However, you can set it to whatever value you like here..
        /// </summary>
        public static string SettingsView_SyncthingAddress_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingAddress_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Syncthing auto-upgrading.
        /// </summary>
        public static string SettingsView_SyncthingDenyUpgrade {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingDenyUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Syncthing from auto-upgrading. This is useful if a new version of Syncthing breaks compatibility with SyncTrayzor. You will need to downgrade the syncthing.exe file in SyncTrayzor&apos;s config folder.
        /// </summary>
        public static string SettingsView_SyncthingDenyUpgrade_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingDenyUpgrade_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Syncthing as a low-priority process.
        /// </summary>
        public static string SettingsView_SyncthingRunLowPriority {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingRunLowPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom home directory for Syncthing..
        /// </summary>
        public static string SettingsView_SyncthingUseCustomHome {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingUseCustomHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will mean that SyncTrayzor will see a different set of configured folders to any other Syncthing instances on your computer..
        /// </summary>
        public static string SettingsView_SyncthingUseCustomHome_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingUseCustomHome_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing.
        /// </summary>
        public static string SettingsView_Tab_Syncthing {
            get {
                return ResourceManager.GetString("SettingsView_Tab_Syncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor.
        /// </summary>
        public static string SettingsView_Tab_SyncTrayzor {
            get {
                return ResourceManager.GetString("SettingsView_Tab_SyncTrayzor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsView_Title {
            get {
                return ResourceManager.GetString("SettingsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing Trace Variables:.
        /// </summary>
        public static string SettingsView_TraceVariables {
            get {
                return ResourceManager.GetString("SettingsView_TraceVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use my computer&apos;s language, where available. You will need to restart SyncTrayzor for this to take effect.
        /// </summary>
        public static string SettingsView_UseComputerCulture {
            get {
                return ResourceManager.GetString("SettingsView_UseComputerCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid URL.
        /// </summary>
        public static string SettingsView_Validation_InvalidUrl {
            get {
                return ResourceManager.GetString("SettingsView_Validation_InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should not be empty.
        /// </summary>
        public static string SettingsView_Validation_NotShouldBeEmpty {
            get {
                return ResourceManager.GetString("SettingsView_Validation_NotShouldBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following folders will be watched for changes, which avoids polling..
        /// </summary>
        public static string SettingsView_WatchedFolders_Explanation {
            get {
                return ResourceManager.GetString("SettingsView_WatchedFolders_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders unavailable. Please start Syncthing.
        /// </summary>
        public static string SettingsView_WatchedFolders_Unavailable {
            get {
                return ResourceManager.GetString("SettingsView_WatchedFolders_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string ShellView_Menu_File {
            get {
                return ResourceManager.GetString("ShellView_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string ShellView_Menu_File_Exit {
            get {
                return ResourceManager.GetString("ShellView_Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string ShellView_Menu_File_Settings {
            get {
                return ResourceManager.GetString("ShellView_Menu_File_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string ShellView_Menu_Help {
            get {
                return ResourceManager.GetString("ShellView_Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string ShellView_Menu_Help_About {
            get {
                return ResourceManager.GetString("ShellView_Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Syncthing.
        /// </summary>
        public static string ShellView_Menu_Syncthing {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Kill.
        /// </summary>
        public static string ShellView_Menu_Syncthing_Kill {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_Kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill _all Syncthing processes.
        /// </summary>
        public static string ShellView_Menu_Syncthing_KillAll {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_KillAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open in external browser.
        /// </summary>
        public static string ShellView_Menu_Syncthing_OpenExternal {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_OpenExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Refresh browser.
        /// </summary>
        public static string ShellView_Menu_Syncthing_Refresh {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R_estart.
        /// </summary>
        public static string ShellView_Menu_Syncthing_Restart {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Start.
        /// </summary>
        public static string ShellView_Menu_Syncthing_Start {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_top.
        /// </summary>
        public static string ShellView_Menu_Syncthing_Stop {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentDescriptionLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentHomepageLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentHomepageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentLicenseLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentLicenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Text:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentLicenseTextLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentLicenseTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentNameLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentNotesLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentNotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor is built using many open-source components, and would not exist without them.
        ///Details on each component, and its license text, are shown below..
        /// </summary>
        public static string ThirdPartyComponentsView_Intro {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Party Components.
        /// </summary>
        public static string ThirdPartyComponentsView_Title {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translator attributation field. Please see the description..
        /// </summary>
        public static string TranslatorAttributation {
            get {
                return ResourceManager.GetString("TranslatorAttributation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} connected.
        /// </summary>
        public static string TrayIcon_Balloon_DeviceConnected_Message {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_DeviceConnected_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Connected.
        /// </summary>
        public static string TrayIcon_Balloon_DeviceConnected_Title {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_DeviceConnected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} disconnected.
        /// </summary>
        public static string TrayIcon_Balloon_DeviceDisconnected_Message {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_DeviceDisconnected_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Disconnected.
        /// </summary>
        public static string TrayIcon_Balloon_DeviceDisconnected_Title {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_DeviceDisconnected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Finished Syncing.
        /// </summary>
        public static string TrayIcon_Balloon_FinishedSyncing_Message {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_FinishedSyncing_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Syncing.
        /// </summary>
        public static string TrayIcon_Balloon_FinishedSyncing_Title {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_FinishedSyncing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close to Tray.
        /// </summary>
        public static string TrayIcon_Menu_CloseToTray {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_CloseToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string TrayIcon_Menu_Exit {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open Folder.
        /// </summary>
        public static string TrayIcon_Menu_OpenFolder {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R_estart.
        /// </summary>
        public static string TrayIcon_Menu_RestartSyncthing {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_RestartSyncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Restore.
        /// </summary>
        public static string TrayIcon_Menu_Restore {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sett_ings.
        /// </summary>
        public static string TrayIcon_Menu_Settings {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Start.
        /// </summary>
        public static string TrayIcon_Menu_StartSyncthing {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_StartSyncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_top.
        /// </summary>
        public static string TrayIcon_Menu_StopSyncthing {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_StopSyncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something went badly wrong.
        ///SyncTrayzor is going to have to close. Sorry about that.
        /// </summary>
        public static string UnhandledExceptionView_IntroMessage {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_IntroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UnhandledExceptionView_LogFileLocation_Post {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_LogFileLocation_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may be asked to provide a log file. You can find this in:.
        /// </summary>
        public static string UnhandledExceptionView_LogFileLocation_Pre {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_LogFileLocation_Pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and include the following information:.
        /// </summary>
        public static string UnhandledExceptionView_PleaseOpenIssue_Post {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_PleaseOpenIssue_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open an issue at.
        /// </summary>
        public static string UnhandledExceptionView_PleaseOpenIssue_Pre {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_PleaseOpenIssue_Pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string UnhandledExceptionView_Title {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string ViewerView_OpenFolder {
            get {
                return ResourceManager.GetString("ViewerView_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Syncthing.
        /// </summary>
        public static string ViewerView_StartSyncthing {
            get {
                return ResourceManager.GetString("ViewerView_StartSyncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing Starting....
        /// </summary>
        public static string ViewerView_SyncthingStarting {
            get {
                return ResourceManager.GetString("ViewerView_SyncthingStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing Stopped.
        /// </summary>
        public static string ViewerView_SyncthingStopped {
            get {
                return ResourceManager.GetString("ViewerView_SyncthingStopped", resourceCulture);
            }
        }
    }
}
