//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncTrayzor.Properties.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SyncTrayzor.Properties.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Antony Male..
        /// </summary>
        public static string AboutView_CreatedByAuthor {
            get {
                return ResourceManager.GetString("AboutView_CreatedByAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string AboutView_DownloadNewVersion {
            get {
                return ResourceManager.GetString("AboutView_DownloadNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available: {0}.
        /// </summary>
        public static string AboutView_NewAppVersionAvailable {
            get {
                return ResourceManager.GetString("AboutView_NewAppVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released under the MIT license..
        /// </summary>
        public static string AboutView_ReleasedLicense {
            get {
                return ResourceManager.GetString("AboutView_ReleasedLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Open Source Licenses.
        /// </summary>
        public static string AboutView_ShowOtherLicenses {
            get {
                return ResourceManager.GetString("AboutView_ShowOtherLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing Version: {0}.
        /// </summary>
        public static string AboutView_SyncthingVersion {
            get {
                return ResourceManager.GetString("AboutView_SyncthingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string AboutView_Version {
            get {
                return ResourceManager.GetString("AboutView_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Generic_Dialog_Close {
            get {
                return ResourceManager.GetString("Generic_Dialog_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string Menu_File_Exit {
            get {
                return ResourceManager.GetString("Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string Menu_File_Settings {
            get {
                return ResourceManager.GetString("Menu_File_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string Menu_Help_About {
            get {
                return ResourceManager.GetString("Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Syncthing.
        /// </summary>
        public static string Menu_Syncthing {
            get {
                return ResourceManager.GetString("Menu_Syncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Kill.
        /// </summary>
        public static string Menu_Syncthing_Kill {
            get {
                return ResourceManager.GetString("Menu_Syncthing_Kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill _all Syncthing processes.
        /// </summary>
        public static string Menu_Syncthing_KillAll {
            get {
                return ResourceManager.GetString("Menu_Syncthing_KillAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open in external browser.
        /// </summary>
        public static string Menu_Syncthing_OpenExternal {
            get {
                return ResourceManager.GetString("Menu_Syncthing_OpenExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Refresh browser.
        /// </summary>
        public static string Menu_Syncthing_Refresh {
            get {
                return ResourceManager.GetString("Menu_Syncthing_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Start.
        /// </summary>
        public static string Menu_Syncthing_Start {
            get {
                return ResourceManager.GetString("Menu_Syncthing_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_top.
        /// </summary>
        public static string Menu_Syncthing_Stop {
            get {
                return ResourceManager.GetString("Menu_Syncthing_Stop", resourceCulture);
            }
        }
    }
}
