//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncTrayzor.Properties.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_pt_BR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_pt_BR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SyncTrayzor.Properties.Strings.Resources.pt_BR", typeof(Resources_pt_BR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criado por Antony Male..
        /// </summary>
        public static string AboutView_CreatedByAuthor {
            get {
                return ResourceManager.GetString("AboutView_CreatedByAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir página de download.
        /// </summary>
        public static string AboutView_DownloadNewVersion {
            get {
                return ResourceManager.GetString("AboutView_DownloadNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova versão disponível: {0}.
        /// </summary>
        public static string AboutView_NewAppVersionAvailable {
            get {
                return ResourceManager.GetString("AboutView_NewAppVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenciado sob a Licença MIT..
        /// </summary>
        public static string AboutView_ReleasedLicense {
            get {
                return ResourceManager.GetString("AboutView_ReleasedLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar licenças Código Aberto (Open Source).
        /// </summary>
        public static string AboutView_ShowOtherLicenses {
            get {
                return ResourceManager.GetString("AboutView_ShowOtherLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing versão: {0}.
        /// </summary>
        public static string AboutView_SyncthingVersion {
            get {
                return ResourceManager.GetString("AboutView_SyncthingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desconhecido.
        /// </summary>
        public static string AboutView_UnknownVersion {
            get {
                return ResourceManager.GetString("AboutView_UnknownVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versão: {0}.
        /// </summary>
        public static string AboutView_Version {
            get {
                return ResourceManager.GetString("AboutView_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você tem certeza que deseja finalizar todos os processos do Syncthing, inclusive aqueles não gerenciados pelo SyncTrayzor?.
        /// </summary>
        public static string Dialog_ConfirmKillAllProcesses_Message {
            get {
                return ResourceManager.GetString("Dialog_ConfirmKillAllProcesses_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza?.
        /// </summary>
        public static string Dialog_ConfirmKillAllProcesses_Title {
            get {
                return ResourceManager.GetString("Dialog_ConfirmKillAllProcesses_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing falhou ao iniciar.
        ///
        ///Por favor, leia o histórico a fim de determinar a causa.
        ///
        ///Se uma linha contendo &quot;FATAL: Cannot open database&quot; (erro fatal: banco de dados não pode ser aberto), por favor feche todas as instâncias abertas do Syncthing. Se o SyncTrayzor travou anteriormente, podem haver processos órfãos (isolados) ainda ativos do Syncthing. Por favor, utilize a opção &quot;Syncthing -&gt; Finalizar todos os processos do Syncthing&quot; no menu a fim de finalizá-los. Então, selecione &quot;Syncthing -&gt; Iniciar&quot; a f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Dialog_FailedToStartSyncthing_Message {
            get {
                return ResourceManager.GetString("Dialog_FailedToStartSyncthing_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing falhou ao iniciar.
        /// </summary>
        public static string Dialog_FailedToStartSyncthing_Title {
            get {
                return ResourceManager.GetString("Dialog_FailedToStartSyncthing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível iniciar Syncthing: {0}
        ///
        ///A razão pode ser o Windows configurado para proibir a execução de programas em AppData, ou porque há anti-malware instalado (e.g., CryptoPrevent) que impede a execução de programas em AppData.
        ///
        ///Por favor, ajuste sua configuração ou listas de permissão para permitir a execução de &apos;{1}&apos;.
        /// </summary>
        public static string Dialog_SyncthingBlockedByGroupPolicy_Message {
            get {
                return ResourceManager.GetString("Dialog_SyncthingBlockedByGroupPolicy_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro iniciando Syntthing.
        /// </summary>
        public static string Dialog_SyncthingBlockedByGroupPolicy_Title {
            get {
                return ResourceManager.GetString("Dialog_SyncthingBlockedByGroupPolicy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start Syncthing: {0}. Please see Syncthing&apos;s console output for clues..
        /// </summary>
        public static string Dialog_SyncthingDidNotStart_Message {
            get {
                return ResourceManager.GetString("Dialog_SyncthingDidNotStart_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing didn&apos;t start correctly.
        /// </summary>
        public static string Dialog_SyncthingDidNotStart_Title {
            get {
                return ResourceManager.GetString("Dialog_SyncthingDidNotStart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string FileTranfersTrayView_Header_Downloading {
            get {
                return ResourceManager.GetString("FileTranfersTrayView_Header_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (deleted).
        /// </summary>
        public static string FileTransfersTrayView_Deleted {
            get {
                return ResourceManager.GetString("FileTransfersTrayView_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0}/{1} ({2}/s).
        /// </summary>
        public static string FileTransfersTrayView_Downloading_RateKnown {
            get {
                return ResourceManager.GetString("FileTransfersTrayView_Downloading_RateKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0}/{1}.
        /// </summary>
        public static string FileTransfersTrayView_Downloading_RateUnknown {
            get {
                return ResourceManager.GetString("FileTransfersTrayView_Downloading_RateUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string FileTransfersTrayView_Error {
            get {
                return ResourceManager.GetString("FileTransfersTrayView_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Updated.
        /// </summary>
        public static string FileTransfersTrayView_Header_RecentlyUpdated {
            get {
                return ResourceManager.GetString("FileTransfersTrayView_Header_RecentlyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In: {0}/s.
        /// </summary>
        public static string FileTransfersTrayView_InConnectionRate {
            get {
                return ResourceManager.GetString("FileTransfersTrayView_InConnectionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recent file transfers.
        /// </summary>
        public static string FileTransfersTrayView_NothingToShow {
            get {
                return ResourceManager.GetString("FileTransfersTrayView_NothingToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out: {0}/s.
        /// </summary>
        public static string FileTransfersTrayView_OutConnectionRate {
            get {
                return ResourceManager.GetString("FileTransfersTrayView_OutConnectionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        public static string FileTransfersTrayView_Starting {
            get {
                return ResourceManager.GetString("FileTransfersTrayView_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        public static string Generic_Copy {
            get {
                return ResourceManager.GetString("Generic_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu_t.
        /// </summary>
        public static string Generic_Cut {
            get {
                return ResourceManager.GetString("Generic_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Generic_Dialog_Cancel {
            get {
                return ResourceManager.GetString("Generic_Dialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        public static string Generic_Dialog_Close {
            get {
                return ResourceManager.GetString("Generic_Dialog_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Generic_Dialog_No {
            get {
                return ResourceManager.GetString("Generic_Dialog_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Generic_Dialog_OK {
            get {
                return ResourceManager.GetString("Generic_Dialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string Generic_Dialog_Save {
            get {
                return ResourceManager.GetString("Generic_Dialog_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Generic_Dialog_Yes {
            get {
                return ResourceManager.GetString("Generic_Dialog_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Paste.
        /// </summary>
        public static string Generic_Paste {
            get {
                return ResourceManager.GetString("Generic_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não me lembrar novamente.
        /// </summary>
        public static string NewVersionAlertView_Button_DontRemind {
            get {
                return ResourceManager.GetString("NewVersionAlertView_Button_DontRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir página de download.
        /// </summary>
        public static string NewVersionAlertView_Button_Download {
            get {
                return ResourceManager.GetString("NewVersionAlertView_Button_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalar agora.
        /// </summary>
        public static string NewVersionAlertView_Button_Install {
            get {
                return ResourceManager.GetString("NewVersionAlertView_Button_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lembrar-me depois.
        /// </summary>
        public static string NewVersionAlertView_Button_RemindLater {
            get {
                return ResourceManager.GetString("NewVersionAlertView_Button_RemindLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histórico de mudanças:.
        /// </summary>
        public static string NewVersionAlertView_Changelog {
            get {
                return ResourceManager.GetString("NewVersionAlertView_Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Não me lembrar novamente&quot; silenciará avisos para esta versão. Você pode desabilitar os avisos de novas versões, permanentemente, a partir da página de Configurações. Visite Ajuda -&gt; Sobre para verificar se há nova versão disponível..
        /// </summary>
        public static string NewVersionAlertView_DontRemindMeExplanation {
            get {
                return ResourceManager.GetString("NewVersionAlertView_DontRemindMeExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor versão {0} está disponível!.
        /// </summary>
        public static string NewVersionAlertView_NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAlertView_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualização do SyncTrayzor disponível.
        /// </summary>
        public static string NewVersionAlertView_Title {
            get {
                return ResourceManager.GetString("NewVersionAlertView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver histórico de mudanças.
        /// </summary>
        public static string NewVersionAlertView_ViewChangelog {
            get {
                return ResourceManager.GetString("NewVersionAlertView_ViewChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor versão {0} foi instalado com sucesso..
        /// </summary>
        public static string NewVersionInstalledView_Message {
            get {
                return ResourceManager.GetString("NewVersionInstalledView_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor atualizado.
        /// </summary>
        public static string NewVersionInstalledView_Title {
            get {
                return ResourceManager.GetString("NewVersionInstalledView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alertar quando uma nova versão do SyncTrayzor estiver disponível.
        /// </summary>
        public static string SettingsView_AlertOnNewVersion {
            get {
                return ResourceManager.GetString("SettingsView_AlertOnNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chave API:.
        /// </summary>
        public static string SettingsView_ApiKey {
            get {
                return ResourceManager.GetString("SettingsView_ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor toma precedência sobre o valor da chave API especificada nas configurações do Syncthing. Entretanto, você pode configurar a chave API para qualquer valor desejado aqui..
        /// </summary>
        public static string SettingsView_ApiKey_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_ApiKey_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar para a área de notificação.
        /// </summary>
        public static string SettingsView_CloseToTray {
            get {
                return ResourceManager.GetString("SettingsView_CloseToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimizar para a área de notificação.
        /// </summary>
        public static string SettingsView_MinimizeToTray {
            get {
                return ResourceManager.GetString("SettingsView_MinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário reiniciar o Syncthing para que as mudanças nestas configurações surtam efeito.
        /// </summary>
        public static string SettingsView_MustRestartSyncthingWarning {
            get {
                return ResourceManager.GetString("SettingsView_MustRestartSyncthingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocultar IDs dos dispositivos no histórico.
        /// </summary>
        public static string SettingsView_ObfuscateDeviceIds {
            get {
                return ResourceManager.GetString("SettingsView_ObfuscateDeviceIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar Ícone na Área de Notificação somente ao fechar.
        /// </summary>
        public static string SettingsView_OnlyShowTrayIconOnClose {
            get {
                return ResourceManager.GetString("SettingsView_OnlyShowTrayIconOnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avançado.
        /// </summary>
        public static string SettingsView_Section_Advanced {
            get {
                return ResourceManager.GetString("SettingsView_Section_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar no login.
        /// </summary>
        public static string SettingsView_Section_StartOnLogin {
            get {
                return ResourceManager.GetString("SettingsView_Section_StartOnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing.
        /// </summary>
        public static string SettingsView_Section_Syncthing {
            get {
                return ResourceManager.GetString("SettingsView_Section_Syncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor.
        /// </summary>
        public static string SettingsView_Section_SyncTrayzor {
            get {
                return ResourceManager.GetString("SettingsView_Section_SyncTrayzor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ícone área de notificação.
        /// </summary>
        public static string SettingsView_Section_TrayIcon {
            get {
                return ResourceManager.GetString("SettingsView_Section_TrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pastas monitoradas.
        /// </summary>
        public static string SettingsView_Section_WatchedFolders {
            get {
                return ResourceManager.GetString("SettingsView_Section_WatchedFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar mensagens de balão &quot;Sincronizado&quot;.
        /// </summary>
        public static string SettingsView_ShowBalloonWhenSynchronized {
            get {
                return ResourceManager.GetString("SettingsView_ShowBalloonWhenSynchronized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar balões de mensagem Conectado/Desconectado.
        /// </summary>
        public static string SettingsView_ShowDeviceConnectivityBalloons {
            get {
                return ResourceManager.GetString("SettingsView_ShowDeviceConnectivityBalloons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar minimizado.
        /// </summary>
        public static string SettingsView_StartMinimized {
            get {
                return ResourceManager.GetString("SettingsView_StartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar automaticamente no login.
        /// </summary>
        public static string SettingsView_StartOnLogin {
            get {
                return ResourceManager.GetString("SettingsView_StartOnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissão negada. Por favor, inicie o SyncTrayzor como Administrador para efetuar estas mudanças..
        /// </summary>
        public static string SettingsView_StartOnLogin_PermissionDenied {
            get {
                return ResourceManager.GetString("SettingsView_StartOnLogin_PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar o Syncthing juntamente com o SyncTrayzor.
        /// </summary>
        public static string SettingsView_StartSyncthingAutomatically {
            get {
                return ResourceManager.GetString("SettingsView_StartSyncthingAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço GUI Listen:.
        /// </summary>
        public static string SettingsView_SyncthingAddress {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor toma precedência sobre o &quot;Endereço GUI Listen&quot; especificado nas configurações do Syncthying. Entretanto, você pode configurar o endereço para qualquer valor desejado aqui..
        /// </summary>
        public static string SettingsView_SyncthingAddress_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingAddress_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parar atualização automática do Syncthing.
        /// </summary>
        public static string SettingsView_SyncthingDenyUpgrade {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingDenyUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parar a atualização automática do Syncthing. Esta opção é útil se uma nova versão do Syncthing não for compatível com o SyncTrayzor. Você terá de instalar uma versão anterior do arquivo syncthing.exe na pasta de configurações do SyncTrayzor.
        /// </summary>
        public static string SettingsView_SyncthingDenyUpgrade_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingDenyUpgrade_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variáveis de ambiente do Syncthing:.
        /// </summary>
        public static string SettingsView_SyncthingEnvironmentalVariables {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingEnvironmentalVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executar Syncthing como processo de baixa prioridade.
        /// </summary>
        public static string SettingsView_SyncthingRunLowPriority {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingRunLowPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Syncthing&apos;s default database location.
        /// </summary>
        public static string SettingsView_SyncthingUseDefaultHome {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingUseDefaultHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If unchecked, this will mean that SyncTrayzor will see a different set of configured folders to any other Syncthing instances on your computer..
        /// </summary>
        public static string SettingsView_SyncthingUseDefaultHome_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingUseDefaultHome_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing.
        /// </summary>
        public static string SettingsView_Tab_Syncthing {
            get {
                return ResourceManager.GetString("SettingsView_Tab_Syncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor.
        /// </summary>
        public static string SettingsView_Tab_SyncTrayzor {
            get {
                return ResourceManager.GetString("SettingsView_Tab_SyncTrayzor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        public static string SettingsView_Title {
            get {
                return ResourceManager.GetString("SettingsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usar o idioma do seu sistema operacional, onde disponível. Você terá de reiniciar o SyncTrayzor para que isto surta efeito.
        /// </summary>
        public static string SettingsView_UseComputerCulture {
            get {
                return ResourceManager.GetString("SettingsView_UseComputerCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório um URL válido.
        /// </summary>
        public static string SettingsView_Validation_InvalidUrl {
            get {
                return ResourceManager.GetString("SettingsView_Validation_InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não pode ser vazio.
        /// </summary>
        public static string SettingsView_Validation_NotShouldBeEmpty {
            get {
                return ResourceManager.GetString("SettingsView_Validation_NotShouldBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório estar no format &apos;VAR=valor VAR2=&quot;valor1 valor2&quot;&apos;.
        /// </summary>
        public static string SettingsView_Validation_SyncthingEnvironmentalVariablesMustHaveFormat {
            get {
                return ResourceManager.GetString("SettingsView_Validation_SyncthingEnvironmentalVariablesMustHaveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As pastas seguintes serão monitoradas para modificações, o que significa que você poderá um intervalo de monitoração mais longo..
        /// </summary>
        public static string SettingsView_WatchedFolders_Explanation {
            get {
                return ResourceManager.GetString("SettingsView_WatchedFolders_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pastas indisponíveis. Por favor, inicie o Syncthing.
        /// </summary>
        public static string SettingsView_WatchedFolders_Unavailable {
            get {
                return ResourceManager.GetString("SettingsView_WatchedFolders_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Arquivo.
        /// </summary>
        public static string ShellView_Menu_File {
            get {
                return ResourceManager.GetString("ShellView_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Sair.
        /// </summary>
        public static string ShellView_Menu_File_Exit {
            get {
                return ResourceManager.GetString("ShellView_Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Configurações.
        /// </summary>
        public static string ShellView_Menu_File_Settings {
            get {
                return ResourceManager.GetString("ShellView_Menu_File_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A_juda.
        /// </summary>
        public static string ShellView_Menu_Help {
            get {
                return ResourceManager.GetString("ShellView_Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_obre.
        /// </summary>
        public static string ShellView_Menu_Help_About {
            get {
                return ResourceManager.GetString("ShellView_Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Syncthing.
        /// </summary>
        public static string ShellView_Menu_Syncthing {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Finalizar.
        /// </summary>
        public static string ShellView_Menu_Syncthing_Kill {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_Kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizar _todos os processos do Syncthing.
        /// </summary>
        public static string ShellView_Menu_Syncthing_KillAll {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_KillAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Abrir no navegador externo.
        /// </summary>
        public static string ShellView_Menu_Syncthing_OpenExternal {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_OpenExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Recarregar esta página.
        /// </summary>
        public static string ShellView_Menu_Syncthing_Refresh {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R_einiciar.
        /// </summary>
        public static string ShellView_Menu_Syncthing_Restart {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Iniciar.
        /// </summary>
        public static string ShellView_Menu_Syncthing_Start {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Parar.
        /// </summary>
        public static string ShellView_Menu_Syncthing_Stop {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Vizualizar.
        /// </summary>
        public static string ShellView_Menu_View {
            get {
                return ResourceManager.GetString("ShellView_Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console Syncthing.
        /// </summary>
        public static string ShellView_Menu_View_SyncthingConsole {
            get {
                return ResourceManager.GetString("ShellView_Menu_View_SyncthingConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Zoom navegador.
        /// </summary>
        public static string ShellView_Menu_Zoom {
            get {
                return ResourceManager.GetString("ShellView_Menu_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom _dentro.
        /// </summary>
        public static string ShellView_Menu_Zoom_In {
            get {
                return ResourceManager.GetString("ShellView_Menu_Zoom_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom _fora.
        /// </summary>
        public static string ShellView_Menu_Zoom_Out {
            get {
                return ResourceManager.GetString("ShellView_Menu_Zoom_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ressetar.
        /// </summary>
        public static string ShellView_Menu_Zoom_Reset {
            get {
                return ResourceManager.GetString("ShellView_Menu_Zoom_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentDescriptionLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentHomepageLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentHomepageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licença:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentLicenseLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentLicenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto da Licença:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentLicenseTextLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentLicenseTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentNameLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notas:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentNotesLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentNotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor foi construído usando vários components de código aberto, e não poderia existir sem eles.
        ///Detalhes de cada component, bem como as licenças, estão abaixo..
        /// </summary>
        public static string ThirdPartyComponentsView_Intro {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Componentes de Terceiros.
        /// </summary>
        public static string ThirdPartyComponentsView_Title {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        public static string TimeAgo_Days_Plural {
            get {
                return ResourceManager.GetString("TimeAgo_Days_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day ago.
        /// </summary>
        public static string TimeAgo_Days_Singular {
            get {
                return ResourceManager.GetString("TimeAgo_Days_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string TimeAgo_Hours_Plural {
            get {
                return ResourceManager.GetString("TimeAgo_Hours_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour ago.
        /// </summary>
        public static string TimeAgo_Hours_Singular {
            get {
                return ResourceManager.GetString("TimeAgo_Hours_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just now.
        /// </summary>
        public static string TimeAgo_JustNow {
            get {
                return ResourceManager.GetString("TimeAgo_JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        public static string TimeAgo_Minutes_Plural {
            get {
                return ResourceManager.GetString("TimeAgo_Minutes_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 minute ago.
        /// </summary>
        public static string TimeAgo_Minutes_Singular {
            get {
                return ResourceManager.GetString("TimeAgo_Minutes_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years ago.
        /// </summary>
        public static string TimeAgo_Years_Plural {
            get {
                return ResourceManager.GetString("TimeAgo_Years_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 year ago.
        /// </summary>
        public static string TimeAgo_Years_Singular {
            get {
                return ResourceManager.GetString("TimeAgo_Years_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tradução para Português-BR por Marcos Portnoi.
        /// </summary>
        public static string TranslatorAttributation {
            get {
                return ResourceManager.GetString("TranslatorAttributation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} conectado.
        /// </summary>
        public static string TrayIcon_Balloon_DeviceConnected_Message {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_DeviceConnected_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositivo conectado.
        /// </summary>
        public static string TrayIcon_Balloon_DeviceConnected_Title {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_DeviceConnected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} desconectado.
        /// </summary>
        public static string TrayIcon_Balloon_DeviceDisconnected_Message {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_DeviceDisconnected_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositivo desconectado.
        /// </summary>
        public static string TrayIcon_Balloon_DeviceDisconnected_Title {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_DeviceDisconnected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Sincronização terminada.
        /// </summary>
        public static string TrayIcon_Balloon_FinishedSyncing_Message {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_FinishedSyncing_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincronização terminada.
        /// </summary>
        public static string TrayIcon_Balloon_FinishedSyncing_Title {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_FinishedSyncing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar para a área de notificação.
        /// </summary>
        public static string TrayIcon_Menu_CloseToTray {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_CloseToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Sair.
        /// </summary>
        public static string TrayIcon_Menu_Exit {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Abrir pasta.
        /// </summary>
        public static string TrayIcon_Menu_OpenFolder {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R_einiciar Syncthing.
        /// </summary>
        public static string TrayIcon_Menu_RestartSyncthing {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_RestartSyncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Restaurar.
        /// </summary>
        public static string TrayIcon_Menu_Restore {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Configurações.
        /// </summary>
        public static string TrayIcon_Menu_Settings {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Iniciar Syncthing.
        /// </summary>
        public static string TrayIcon_Menu_StartSyncthing {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_StartSyncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Parar Syncthing.
        /// </summary>
        public static string TrayIcon_Menu_StopSyncthing {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_StopSyncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opa! Algum erro aconteceu.
        ///SyncTrayzor terá de fechar. Sinto muito.
        /// </summary>
        public static string UnhandledExceptionView_IntroMessage {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_IntroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UnhandledExceptionView_LogFileLocation_Post {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_LogFileLocation_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você poderá ser solicitado a enviar um arquivo de histórico (log). Você pode achar o arquivo em:.
        /// </summary>
        public static string UnhandledExceptionView_LogFileLocation_Pre {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_LogFileLocation_Pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e inclua as seguintes informações:.
        /// </summary>
        public static string UnhandledExceptionView_PleaseOpenIssue_Post {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_PleaseOpenIssue_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, abra uma requisição em.
        /// </summary>
        public static string UnhandledExceptionView_PleaseOpenIssue_Pre {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_PleaseOpenIssue_Pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro!.
        /// </summary>
        public static string UnhandledExceptionView_Title {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir pasta.
        /// </summary>
        public static string ViewerView_OpenFolder {
            get {
                return ResourceManager.GetString("ViewerView_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Syncthing.
        /// </summary>
        public static string ViewerView_StartSyncthing {
            get {
                return ResourceManager.GetString("ViewerView_StartSyncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando Syncthing....
        /// </summary>
        public static string ViewerView_SyncthingStarting {
            get {
                return ResourceManager.GetString("ViewerView_SyncthingStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing parou.
        /// </summary>
        public static string ViewerView_SyncthingStopped {
            get {
                return ResourceManager.GetString("ViewerView_SyncthingStopped", resourceCulture);
            }
        }
    }
}
