//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncTrayzor.Properties.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_it_IT {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_it_IT() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SyncTrayzor.Properties.Strings.Resources.it_IT", typeof(Resources_it_IT).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creato da Antony Male..
        /// </summary>
        public static string AboutView_CreatedByAuthor {
            get {
                return ResourceManager.GetString("AboutView_CreatedByAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apri Pagina Download.
        /// </summary>
        public static string AboutView_DownloadNewVersion {
            get {
                return ResourceManager.GetString("AboutView_DownloadNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuova versione disponibile : {0}.
        /// </summary>
        public static string AboutView_NewAppVersionAvailable {
            get {
                return ResourceManager.GetString("AboutView_NewAppVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rilasciato sotto la licenza MIT..
        /// </summary>
        public static string AboutView_ReleasedLicense {
            get {
                return ResourceManager.GetString("AboutView_ReleasedLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostra Licenze Open Source.
        /// </summary>
        public static string AboutView_ShowOtherLicenses {
            get {
                return ResourceManager.GetString("AboutView_ShowOtherLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versione Syncthing : {0}.
        /// </summary>
        public static string AboutView_SyncthingVersion {
            get {
                return ResourceManager.GetString("AboutView_SyncthingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sconosciuto.
        /// </summary>
        public static string AboutView_UnknownVersion {
            get {
                return ResourceManager.GetString("AboutView_UnknownVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versione: {0}.
        /// </summary>
        public static string AboutView_Version {
            get {
                return ResourceManager.GetString("AboutView_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sei sicuro di voler terminare tutti i processi Syncthing, anche quelli non gestiti da SyncTrayzor?.
        /// </summary>
        public static string Dialog_ConfirmKillAllProcesses_Message {
            get {
                return ResourceManager.GetString("Dialog_ConfirmKillAllProcesses_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sei Sicuro?.
        /// </summary>
        public static string Dialog_ConfirmKillAllProcesses_Title {
            get {
                return ResourceManager.GetString("Dialog_ConfirmKillAllProcesses_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile avviare Syncthing.
        ///
        ///Prego leggere il log per capirne la causa.
        ///
        ///Se appare l&apos;errore &quot;FATAL:Cannot open database&quot;,  prego chiudere tutte le altre instanze di Syncthing. Se SyncTrayzor ha avuto un precedente crash, ci possono essere dei processi ancora attivi in background. Usare il menu &quot;Syncthing-&gt;Termina tutti i processi Syncthing&quot; per terminarli, e &quot;Syncthing-&gt;Avvia&quot; per riavviare Syncthing..
        /// </summary>
        public static string Dialog_FailedToStartSyncthing_Message {
            get {
                return ResourceManager.GetString("Dialog_FailedToStartSyncthing_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile avviare Syncthing.
        /// </summary>
        public static string Dialog_FailedToStartSyncthing_Title {
            get {
                return ResourceManager.GetString("Dialog_FailedToStartSyncthing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile avviare Syncthing: {0}
        ///
        ///Ciò potrebbe essere perchè Windows, è impostato in modo da vietare l&apos;esecuzione di files in AppData o perchè hai installato un anti-malware (es: CryptoPrevent ) che impedisce l&apos;esecuzione di files in AppData.
        ///
        ///Prego modifica le tue impostazioni / whitelist &apos;{1}&apos; per consentire l&apos;esecuzione.
        /// </summary>
        public static string Dialog_SyncthingBlockedByGroupPolicy_Message {
            get {
                return ResourceManager.GetString("Dialog_SyncthingBlockedByGroupPolicy_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nel lanciare Syncthing.
        /// </summary>
        public static string Dialog_SyncthingBlockedByGroupPolicy_Title {
            get {
                return ResourceManager.GetString("Dialog_SyncthingBlockedByGroupPolicy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla.
        /// </summary>
        public static string Generic_Dialog_Cancel {
            get {
                return ResourceManager.GetString("Generic_Dialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiudi.
        /// </summary>
        public static string Generic_Dialog_Close {
            get {
                return ResourceManager.GetString("Generic_Dialog_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Generic_Dialog_No {
            get {
                return ResourceManager.GetString("Generic_Dialog_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Generic_Dialog_OK {
            get {
                return ResourceManager.GetString("Generic_Dialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salva.
        /// </summary>
        public static string Generic_Dialog_Save {
            get {
                return ResourceManager.GetString("Generic_Dialog_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        public static string Generic_Dialog_Yes {
            get {
                return ResourceManager.GetString("Generic_Dialog_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non ricordarmelo ancora.
        /// </summary>
        public static string NewVersionAlertView_Button_DontRemind {
            get {
                return ResourceManager.GetString("NewVersionAlertView_Button_DontRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apri Pagina dei Download.
        /// </summary>
        public static string NewVersionAlertView_Button_Download {
            get {
                return ResourceManager.GetString("NewVersionAlertView_Button_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installa Ora.
        /// </summary>
        public static string NewVersionAlertView_Button_Install {
            get {
                return ResourceManager.GetString("NewVersionAlertView_Button_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ricordamelo Successivamente.
        /// </summary>
        public static string NewVersionAlertView_Button_RemindLater {
            get {
                return ResourceManager.GetString("NewVersionAlertView_Button_RemindLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note di rilascio:.
        /// </summary>
        public static string NewVersionAlertView_Changelog {
            get {
                return ResourceManager.GetString("NewVersionAlertView_Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Non Ricordarmelo&quot; disabiliterà tutti i promemoria per questa versione. Puoi disattivare in modo permanente i nuovi avvisi nella pagina delle Impostazioni. Controlla Aiuto-&gt; Info per cercare una nuova versione manualmente..
        /// </summary>
        public static string NewVersionAlertView_DontRemindMeExplanation {
            get {
                return ResourceManager.GetString("NewVersionAlertView_DontRemindMeExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La versione {0} di SyncTrayzor è disponibile!.
        /// </summary>
        public static string NewVersionAlertView_NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAlertView_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor Aggiornamento Disponibile.
        /// </summary>
        public static string NewVersionAlertView_Title {
            get {
                return ResourceManager.GetString("NewVersionAlertView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vedi Note di Rilascio.
        /// </summary>
        public static string NewVersionAlertView_ViewChangelog {
            get {
                return ResourceManager.GetString("NewVersionAlertView_ViewChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La versione {0} di SyncTrayzor è stata installata correttamente..
        /// </summary>
        public static string NewVersionInstalledView_Message {
            get {
                return ResourceManager.GetString("NewVersionInstalledView_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor Aggiornato.
        /// </summary>
        public static string NewVersionInstalledView_Title {
            get {
                return ResourceManager.GetString("NewVersionInstalledView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avvisa se una nuova versione di SyncTrayzor è disponibile.
        /// </summary>
        public static string SettingsView_AlertOnNewVersion {
            get {
                return ResourceManager.GetString("SettingsView_AlertOnNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiave API:.
        /// </summary>
        public static string SettingsView_ApiKey {
            get {
                return ResourceManager.GetString("SettingsView_ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor sovrascrive la chiave API specificata nella configurazione di Syncthing. Tuttavia, puoi impostare qualsiasi valore qua..
        /// </summary>
        public static string SettingsView_ApiKey_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_ApiKey_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiudi nella barra delle applicazioni.
        /// </summary>
        public static string SettingsView_CloseToTray {
            get {
                return ResourceManager.GetString("SettingsView_CloseToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimizza nella barra delle applicazioni.
        /// </summary>
        public static string SettingsView_MinimizeToTray {
            get {
                return ResourceManager.GetString("SettingsView_MinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to È necessario riavviare Syncthing affinchè le modifiche a queste impostazioni abbiano effetto.
        /// </summary>
        public static string SettingsView_MustRestartSyncthingWarning {
            get {
                return ResourceManager.GetString("SettingsView_MustRestartSyncthingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offuscare ID dei dispositivi nel log.
        /// </summary>
        public static string SettingsView_ObfuscateDeviceIds {
            get {
                return ResourceManager.GetString("SettingsView_ObfuscateDeviceIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostra Icona nella barra delle applicazioni solo alla chiusura.
        /// </summary>
        public static string SettingsView_OnlyShowTrayIconOnClose {
            get {
                return ResourceManager.GetString("SettingsView_OnlyShowTrayIconOnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avanzate.
        /// </summary>
        public static string SettingsView_Section_Advanced {
            get {
                return ResourceManager.GetString("SettingsView_Section_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avvia al Login.
        /// </summary>
        public static string SettingsView_Section_StartOnLogin {
            get {
                return ResourceManager.GetString("SettingsView_Section_StartOnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing.
        /// </summary>
        public static string SettingsView_Section_Syncthing {
            get {
                return ResourceManager.GetString("SettingsView_Section_Syncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor.
        /// </summary>
        public static string SettingsView_Section_SyncTrayzor {
            get {
                return ResourceManager.GetString("SettingsView_Section_SyncTrayzor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icona barra delle applicazioni.
        /// </summary>
        public static string SettingsView_Section_TrayIcon {
            get {
                return ResourceManager.GetString("SettingsView_Section_TrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartelle Monitorate.
        /// </summary>
        public static string SettingsView_Section_WatchedFolders {
            get {
                return ResourceManager.GetString("SettingsView_Section_WatchedFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostra i messaggi informativi &apos;Sincronizzato&apos;.
        /// </summary>
        public static string SettingsView_ShowBalloonWhenSynchronized {
            get {
                return ResourceManager.GetString("SettingsView_ShowBalloonWhenSynchronized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostra i dispositivi Connessi/Disconnessi nei messaggi informativi.
        /// </summary>
        public static string SettingsView_ShowDeviceConnectivityBalloons {
            get {
                return ResourceManager.GetString("SettingsView_ShowDeviceConnectivityBalloons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avvia Minimizzato.
        /// </summary>
        public static string SettingsView_StartMinimized {
            get {
                return ResourceManager.GetString("SettingsView_StartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avvia in automatico al login.
        /// </summary>
        public static string SettingsView_StartOnLogin {
            get {
                return ResourceManager.GetString("SettingsView_StartOnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permesso negato. Prego avviare SyncTrayzor come Amministratore per cambiare questi parametri..
        /// </summary>
        public static string SettingsView_StartOnLogin_PermissionDenied {
            get {
                return ResourceManager.GetString("SettingsView_StartOnLogin_PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avvia Syncthing quando SyncTrayzor si sta avviando.
        /// </summary>
        public static string SettingsView_StartSyncthingAutomatically {
            get {
                return ResourceManager.GetString("SettingsView_StartSyncthingAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirizzo Di Ascolto GUI:.
        /// </summary>
        public static string SettingsView_SyncthingAddress {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor sovrascrive l&apos;indirizzo di ascolto GUI specificato nella configurazione di Syncthing. Tuttavia, puoi impostarlo qua..
        /// </summary>
        public static string SettingsView_SyncthingAddress_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingAddress_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferma l&apos;auto-aggiornamento di Syncthing.
        /// </summary>
        public static string SettingsView_SyncthingDenyUpgrade {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingDenyUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferma l&apos;auto-aggiornamento di Syncthing. Questo è utile se una nuova versione di Syncthing non è retrocompatibile con SyncTrayzor. Dovrai effettuare il downgrade del file syncthing.exe nella cartella di configurazione di SyncTrayzor.
        /// </summary>
        public static string SettingsView_SyncthingDenyUpgrade_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingDenyUpgrade_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variabili Di Ambiente Synchting:.
        /// </summary>
        public static string SettingsView_SyncthingEnvironmentalVariables {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingEnvironmentalVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esegui Syncthing come un processo a bassa priorità.
        /// </summary>
        public static string SettingsView_SyncthingRunLowPriority {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingRunLowPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usa una cartella personalizzata come Home per Syncthing..
        /// </summary>
        public static string SettingsView_SyncthingUseCustomHome {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingUseCustomHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciò significa che SyncTrayzor vedrà un differente set di cartelle configurate per qualsiasi altra instanza di Syncthing sul computer..
        /// </summary>
        public static string SettingsView_SyncthingUseCustomHome_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_SyncthingUseCustomHome_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing.
        /// </summary>
        public static string SettingsView_Tab_Syncthing {
            get {
                return ResourceManager.GetString("SettingsView_Tab_Syncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor.
        /// </summary>
        public static string SettingsView_Tab_SyncTrayzor {
            get {
                return ResourceManager.GetString("SettingsView_Tab_SyncTrayzor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impostazioni.
        /// </summary>
        public static string SettingsView_Title {
            get {
                return ResourceManager.GetString("SettingsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usa la lingua predefinita del computer, quando disponibile. Dovrai riavviare SyncTrayzor affinchè le modifiche abbiano effetto..
        /// </summary>
        public static string SettingsView_UseComputerCulture {
            get {
                return ResourceManager.GetString("SettingsView_UseComputerCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve essere un URL valido.
        /// </summary>
        public static string SettingsView_Validation_InvalidUrl {
            get {
                return ResourceManager.GetString("SettingsView_Validation_InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non può essere vuoto.
        /// </summary>
        public static string SettingsView_Validation_NotShouldBeEmpty {
            get {
                return ResourceManager.GetString("SettingsView_Validation_NotShouldBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve essere nel formato &apos;VAR=valore VAR2=&quot;val1 val2&quot;&apos;.
        /// </summary>
        public static string SettingsView_Validation_SyncthingEnvironmentalVariablesMustHaveFormat {
            get {
                return ResourceManager.GetString("SettingsView_Validation_SyncthingEnvironmentalVariablesMustHaveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le seguenti cartelle saranno controllate per eventuali cambiamenti, significa che puoi impostare un lungo intervallo di polling..
        /// </summary>
        public static string SettingsView_WatchedFolders_Explanation {
            get {
                return ResourceManager.GetString("SettingsView_WatchedFolders_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartelle non disponibili. Prego avviare Synchting..
        /// </summary>
        public static string SettingsView_WatchedFolders_Unavailable {
            get {
                return ResourceManager.GetString("SettingsView_WatchedFolders_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string ShellView_Menu_File {
            get {
                return ResourceManager.GetString("ShellView_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Esci.
        /// </summary>
        public static string ShellView_Menu_File_Exit {
            get {
                return ResourceManager.GetString("ShellView_Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Impostazioni.
        /// </summary>
        public static string ShellView_Menu_File_Settings {
            get {
                return ResourceManager.GetString("ShellView_Menu_File_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ai_uto.
        /// </summary>
        public static string ShellView_Menu_Help {
            get {
                return ResourceManager.GetString("ShellView_Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_nfo.
        /// </summary>
        public static string ShellView_Menu_Help_About {
            get {
                return ResourceManager.GetString("ShellView_Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Syncthing.
        /// </summary>
        public static string ShellView_Menu_Syncthing {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Termina.
        /// </summary>
        public static string ShellView_Menu_Syncthing_Kill {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_Kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_ermina tutti i processi Syncthing.
        /// </summary>
        public static string ShellView_Menu_Syncthing_KillAll {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_KillAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A_pri nel browser esterno.
        /// </summary>
        public static string ShellView_Menu_Syncthing_OpenExternal {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_OpenExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A_ggiorna browser.
        /// </summary>
        public static string ShellView_Menu_Syncthing_Refresh {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Riavvio.
        /// </summary>
        public static string ShellView_Menu_Syncthing_Restart {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Avvia.
        /// </summary>
        public static string ShellView_Menu_Syncthing_Start {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fer_ma.
        /// </summary>
        public static string ShellView_Menu_Syncthing_Stop {
            get {
                return ResourceManager.GetString("ShellView_Menu_Syncthing_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M_ostra.
        /// </summary>
        public static string ShellView_Menu_View {
            get {
                return ResourceManager.GetString("ShellView_Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing Console.
        /// </summary>
        public static string ShellView_Menu_View_SyncthingConsole {
            get {
                return ResourceManager.GetString("ShellView_Menu_View_SyncthingConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Zoom Browser.
        /// </summary>
        public static string ShellView_Menu_Zoom {
            get {
                return ResourceManager.GetString("ShellView_Menu_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In_grandisci.
        /// </summary>
        public static string ShellView_Menu_Zoom_In {
            get {
                return ResourceManager.GetString("ShellView_Menu_Zoom_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ri_duci.
        /// </summary>
        public static string ShellView_Menu_Zoom_Out {
            get {
                return ResourceManager.GetString("ShellView_Menu_Zoom_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re_set.
        /// </summary>
        public static string ShellView_Menu_Zoom_Reset {
            get {
                return ResourceManager.GetString("ShellView_Menu_Zoom_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrizione:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentDescriptionLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentHomepageLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentHomepageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenza:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentLicenseLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentLicenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testo Licenza:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentLicenseTextLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentLicenseTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentNameLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        public static string ThirdPartyComponentsView_ComponentNotesLabel {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_ComponentNotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncTrayzor è compilato usando molti componenti open-source, e non esisterebbe senza di essi.
        ///I dettagli di ogni componente, e le licenze sono indicati di seguito..
        /// </summary>
        public static string ThirdPartyComponentsView_Intro {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Componenti Di Terze Parti.
        /// </summary>
        public static string ThirdPartyComponentsView_Title {
            get {
                return ResourceManager.GetString("ThirdPartyComponentsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian translation by stukdev.
        /// </summary>
        public static string TranslatorAttributation {
            get {
                return ResourceManager.GetString("TranslatorAttributation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} connesso.
        /// </summary>
        public static string TrayIcon_Balloon_DeviceConnected_Message {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_DeviceConnected_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositivo Connesso.
        /// </summary>
        public static string TrayIcon_Balloon_DeviceConnected_Title {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_DeviceConnected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} disconnesso.
        /// </summary>
        public static string TrayIcon_Balloon_DeviceDisconnected_Message {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_DeviceDisconnected_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositivo Disconnesso.
        /// </summary>
        public static string TrayIcon_Balloon_DeviceDisconnected_Title {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_DeviceDisconnected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Sincronizzazione Completata.
        /// </summary>
        public static string TrayIcon_Balloon_FinishedSyncing_Message {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_FinishedSyncing_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincronizzazione Completata.
        /// </summary>
        public static string TrayIcon_Balloon_FinishedSyncing_Title {
            get {
                return ResourceManager.GetString("TrayIcon_Balloon_FinishedSyncing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiudi nella barra delle applicazioni.
        /// </summary>
        public static string TrayIcon_Menu_CloseToTray {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_CloseToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Esci.
        /// </summary>
        public static string TrayIcon_Menu_Exit {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Apri Cartella.
        /// </summary>
        public static string TrayIcon_Menu_OpenFolder {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Riavvia Syncthing.
        /// </summary>
        public static string TrayIcon_Menu_RestartSyncthing {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_RestartSyncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ripristina.
        /// </summary>
        public static string TrayIcon_Menu_Restore {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Impostazioni.
        /// </summary>
        public static string TrayIcon_Menu_Settings {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Avvia Syncthing.
        /// </summary>
        public static string TrayIcon_Menu_StartSyncthing {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_StartSyncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ferma Syncthing.
        /// </summary>
        public static string TrayIcon_Menu_StopSyncthing {
            get {
                return ResourceManager.GetString("TrayIcon_Menu_StopSyncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Qualcosa è andato storto.
        ///SyncTrayzor dovrà essere terminato. Ci scusiamo..
        /// </summary>
        public static string UnhandledExceptionView_IntroMessage {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_IntroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UnhandledExceptionView_LogFileLocation_Post {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_LogFileLocation_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebbe essere richiesto un file di log. Lo puoi trovare in:.
        /// </summary>
        public static string UnhandledExceptionView_LogFileLocation_Pre {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_LogFileLocation_Pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e aggiungi le seguenti informazioni:.
        /// </summary>
        public static string UnhandledExceptionView_PleaseOpenIssue_Post {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_PleaseOpenIssue_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prego aprire un ticket a.
        /// </summary>
        public static string UnhandledExceptionView_PleaseOpenIssue_Pre {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_PleaseOpenIssue_Pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore!.
        /// </summary>
        public static string UnhandledExceptionView_Title {
            get {
                return ResourceManager.GetString("UnhandledExceptionView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apri Cartella.
        /// </summary>
        public static string ViewerView_OpenFolder {
            get {
                return ResourceManager.GetString("ViewerView_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avvia Syncthing.
        /// </summary>
        public static string ViewerView_StartSyncthing {
            get {
                return ResourceManager.GetString("ViewerView_StartSyncthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing in avvio....
        /// </summary>
        public static string ViewerView_SyncthingStarting {
            get {
                return ResourceManager.GetString("ViewerView_SyncthingStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncthing fermato..
        /// </summary>
        public static string ViewerView_SyncthingStopped {
            get {
                return ResourceManager.GetString("ViewerView_SyncthingStopped", resourceCulture);
            }
        }
    }
}
